fine-ants/FineAnts-was

.github/workflows/cicd.yml, .gitignore, .gitmodules, Dockerfile, build.gradle, docker-compose-analyze.yml, src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java, src/main/java/codesquad/fineants/spring/api/kis/KisService.java, src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java, src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java, src/main/java/codesquad/fineants/spring/api/kis/manager/LastDayClosingPriceManager.java, src/main/java/codesquad/fineants/spring/api/kis/response/LastDayClosingPriceResponse.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsResponse.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java, src/main/resources/application.yml, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
-  당일 손익에서 당일 변동 금액으로 주석 수정
- 당일 변동 금액 공식에 맞게 코드 수정
- 주식의 전일 종가를 저장하기 위해서 LastDayClosingPriceManager라는 매니저 객체 생성
다음 포트폴리오 상세 조회 및 종목 조회 실행 결과를 보면 삼성전자 종목의 전일 종가는 "72200"인 상태이고 주식 현재가(currentPrice)는 72800원으로써 당일 변동 금액은 600임을 볼 수 있습니다. 당일 변동율은 0.83%로써 정수단위만 응답하여 0을 반환하였습니다.
=> [fix] 포트폴리오 종목(PortfolioHolding) 당일변동금액 문제해결

build.gradle, env, src/main/java/codesquad/fineants/spring/config/CacheConfig.java, src/main/java/codesquad/fineants/spring/config/FilterConfig.java, src/main/java/codesquad/fineants/spring/config/SecurityConfig.java, src/main/java/codesquad/fineants/spring/config/WebConfig.java, src/main/java/codesquad/fineants/spring/filter/CorsFilter.java, src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
- AS-IS : 인증 처리 필터를 WebConfig, FilterConfig에 등록해서 URL 별 인증 구현
- TO-BE : SecurityConfig 파일에서 각각의 필터 등록(인증/로그아웃/Cors) 및 인증을 거쳐야하는 URL 지정 
1. 기존에 인증을 구현하셨던 WebConfig, FilterConfig 파일과 일부 코드를 삭제 대신 주석처리 해두었습니다. 
=> 다른 분들 개발 진행 방식에 따라 삭제하고 Push 할지 정하도록 하겠습니다!
2. URL 별 인가 처리는 아직 진행하지 않았습니다. 
=> 추후 진행 예정(사용자 별 Role 이 정해진 후)
=> #15 feat: spring security 적용

src/main/java/codesquad/fineants/spring/config/WebConfig.java
- oauth 로그인까지는 잘 수행되지만 로그아웃이 수행되지 않습니다.
- 컨트롤러 매핑 메소드에 accessToken을 전달하지 않고 있습니다.
- 기존에는 LogoutInterceptor에 의해서 컨트롤러 전달전에 Authorization 헤더에서 accessToken을 파싱하여 RequestAttribute로 설정하였지만 security 라이브러리 도입 과정에서 설정이 빠진 것을 확인하였습니다.
- LogoutInterceptor를 설정에 추가합니다.
```java
@Configuration
public class WebConfig implements WebMvcConfigurer {
@Override
public void addInterceptors(InterceptorRegistry registry) {
registry.addInterceptor(new LogoutInterceptor())
.addPathPatterns("/api/auth/logout");
}
}
```
=> [fix] 로그아웃 문제 해결

src/main/java/codesquad/fineants/spring/config/WebConfig.java
- 로그인 후 포트폴리오 목록 조회와 같이 컨트롤러 매핑 메소드에 AuthMember 매개변수에 로그인한 사용자 정보를 넣어주지 못하고 있습니다.
- seucirty 라이브러리 적용 과정에서 AuthPrincipalArgumentResolver를 설정한 WebConfig 파일이 제거되면서 설정되지 않아서 입니다.
- WebConfig 파일에 AuthPrincipalArgumentResolver를 설정 추가합니다.
```java
@Configuration
@RequiredArgsConstructor
public class WebConfig implements WebMvcConfigurer {
private final AuthPrincipalArgumentResolver authPrincipalArgumentResolver;
// ...
@Override
public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
resolvers.add(authPrincipalArgumentResolver);
}
}
```
=> [fix] AuthMember 문제 해결

docker-compose-analyze.yml, docker-compose-dev.yml, docker-compose.yml, redis.conf
개발 배포 서버에서 카카오 소셜 로그인 수행시 다음과 같은 에러가 발생하였습니다.
redis는 데이터 영속화를 위해서 BGSAVE 명령어를 이용하여 redis db의 스냅샷을 작성합니다. 그런데 BGSAVE 명령어가 실패하게 되면 Redis는 설정에 따라서 Write 명령어를 전부 거부하게 됩니다.
reids.c를 보면 processCommand에는 다음과 같은 코드가 존재합니다.
```c
if (server.stop_writes_on_bgsave_err &&
server.saveparamslen > 0
&& server.lastbgsave_status == REDIS_ERR &&
c->cmd->flags & REDIS_CMD_WRITE){
flagTransaction(c);
addReply(c, shared.bgsaveerr);
return REDIS_OK;
}
```
- 조건문에서 stop_writes_on_bgsave_err가 true인 경우 RDB 생성에 실패 했을 때 Write는 전부 거부되는 것을 확인할 수 있습니다. 
redis를 캐시 용도로만 사용한다면 `config set stop-writes-on-bgsave-error no` 명령어를 통해서 RDB 스냅샷을 생성하지 않도록 합니다. 저희 인프라 같은 경우 docker-compose를 통해서 redis 컨테이너를 띄우기 때문에 docker-compose-dev.yml 파일에 볼륨을 이용해서 설정 파일을 마운트하여 RDB 스냅샷을 설정하지 않도록 합니다.
redis.conf
```
stop-writes-on-bgsave-error no
``` …
=> [bug] redis 컨테이너 RDB 스냅샷이 저장되지 않도록 설정 파일 추가

src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/StockMarketChecker.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
- 포트폴리오 상세 조회 및 종목 조회에서 각 종목별 배당금 내역을 삭제하였습니다.
- 포트폴리오 상세 조회 및 종목 조회 테스트 코드에서 샘플 데이터 생성 하는 부분을 별도의 메소드로 분리하였습니다.
- 장시간 내에서는 5초에 한번씩 지속적으로 응답하도록 하고 장시간이 끝나면 한번의 SSE 응답하고 HTTP 연결을 끊도록 변경하였습니다.
-  프론트 엔드 팀원들과 의논하여 요구사항이 변경되어 적용하였습니다.
- 장시간에 따라서 SSE 응답을 위한 테스크를 생성하는데 중복된 메소드가 발생하였습니다. 별도의 객체로 분리하여 제거하여야 합니다.
=> [feat] 포트폴리오 상세 조회 및 종목 조회 응답 형식 변경

src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
- 포트폴리오 상세 조회 SSE 응답시 메시지 이름을 "sse event - myPortfolioStocks"에서 "portfolioDetails"로 변경하였습니다.
=> [fix] sse 응답 메시지 이름 변경

src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistory.java, src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java, src/main/java/codesquad/fineants/spring/api/dashboard/controller/DashboardRestController.java, src/main/java/codesquad/fineants/spring/api/dashboard/response/DashboardLineChartResponse.java, src/main/java/codesquad/fineants/spring/api/dashboard/response/DashboardPieChartResponse.java, src/main/java/codesquad/fineants/spring/api/dashboard/response/OverviewResponse.java, src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java, src/main/java/codesquad/fineants/spring/api/success/code/DashboardSuccessCode.java, src/test/java/codesquad/fineants/spring/api/dashboard/DashboardServiceTest.java
- 대시보드
- 오버뷰 : 모든 포트폴리오의 평가금액, 투자금액, 총손익금액, 총손익율, 총연배당금, 총연배당율을 합한 금액을 조회하는 API
- api : GET /api/dashboard/overview 
- 포트폴리오 파이 차트 : 사용자의 포트폴리오들을 대상으로 파이 차트 구성하는 API
- api : GET /api/dashboard/pieChart 
- 라인 차트 : 일자별 오버뷰 데이터에 대한 총 자산 그래프 데이터 API
- api : /api/dashboard/lineChart
=> [feat] 대시보드 구현

src/main/java/codesquad/fineants/domain/stock/Market.java, src/main/java/codesquad/fineants/domain/stock/Stock.java, src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java, src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java, src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java, src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java, src/main/java/codesquad/fineants/spring/config/SpringConfig.java, src/main/resources/application.yml, src/main/resources/db/mysql/data.sql, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java
- 포트폴리오 추가시 목록에 포함된 증권사 데이터들만 들어갈 수 있도록 검증 코드를 구현하였습니다.
- 증권사 정보를 객체에 담을 수 있도록 PortfolioProperties 추가
- Stock 엔티티의 Market enum 멤버에 대해서 Converter 추가
다음 실행 결과는 포트폴리오 추가시 목록에 포함되어 있지 않은 데이터를 입력하였을 때 실행 결과입니다.
=> [feat] 포트폴리오에 증권사 정보 검증 구현

src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/domain/stock/Market.java, src/main/java/codesquad/fineants/domain/stock/Stock.java, src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java, src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java, src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java, src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java, src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java, src/main/java/codesquad/fineants/spring/config/SpringConfig.java, src/main/resources/application.yml, src/main/resources/db/mysql/data.sql, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
- 포트폴리오 상세 조회 API 응답값의 프로퍼티를 변경하였습니다.
- totalAunnalDividend -> annualDividend
- totalAnnualDividendYield ->  annualDividendYield
=> [fix] 포트폴리오 상세 조회 응답 프로퍼티 변경

src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/domain/stock/Market.java, src/main/java/codesquad/fineants/domain/stock/Stock.java, src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java, src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java, src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java, src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java, src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java, src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java, src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java, src/main/java/codesquad/fineants/spring/config/SpringConfig.java, src/main/resources/application.yml, src/main/resources/db/mysql/data.sql, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
- 포트폴리오 수정 서비스 수행중 포트폴리오 이름이 그대로인 경우 중복 검증을 수행하는 부분을 수정하였습니다. 조건문을 추가하여 이름이 그대로인 경우 중복 검증을 수행하지 않도록 수정하였습니다.
- 포트폴리오 수정 서비스에 대한 테스트 코드 추가
- MethodArgumentNotValidException 핸들러 버그 수정
=> [fix] 포트폴리오 수정시 이름이 그대로인 경우 중복되는 문제 해결

src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
- 포트폴리오 삭제시 포트폴리오 손익 내역 데이터가 삭제되도록 로직을 변경했습니다.
- 서비스 테스트코드에 손익 내역 데이터가 삭제되었는지 확인하는 로직을 추가했습니다.
=> [fix] delete portfolioGainHisotry when deleting portfolio

src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java, src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java, src/main/java/codesquad/fineants/spring/api/watch_list/response/ReadWatchListsResponse.java, src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
- GET /api/watchlists의 응답 형식을 변경했습니다.
=> [fix] get rid of watchlists in response

build.gradle, src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java, src/main/java/codesquad/fineants/spring/api/kis/client/KisAccessToken.java, src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java, src/main/java/codesquad/fineants/spring/api/kis/config/KisConfig.java, src/main/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManager.java, src/main/java/codesquad/fineants/spring/api/kis/properties/OauthKisProperties.java, src/main/java/codesquad/fineants/spring/api/kis/service/KisRedisService.java, src/main/java/codesquad/fineants/spring/config/OauthConfig.java, src/test/java/codesquad/fineants/spring/api/kis/client/KisClientTest.java, src/test/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManagerTest.java, src/test/java/codesquad/fineants/spring/api/kis/service/KisRedisServiceTest.java
- retryWhen operator를 사용하여 서버 시작시 한국투자증권의 액세스 토큰 재발급에 실패하는 경우 1분 간격으로 성공할때까지 재시도하도록 변경하였습니다.
- mockwebserver 의존성 라이브러리를 추가하여 재발급 관련 테스트 코드를 구현하였습니다. 
- Hikari Connection Pool 고갈 문제 해결
=> [fix] 서버 시작시 한국투자증권 액세스 토큰 재발급 문제 해결

src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java, src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioCreateRequest.java, src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioModifyRequest.java, src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationService.java, src/main/java/codesquad/fineants/spring/api/portfolio_notification/manager/MailRedisManager.java, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
- 포트폴리오 추가 및 수정시 예산, 목표수익금액, 최대손실금액은 0원도 입력받을 수 있도록 변경하였습니다.
- 메일 알림 서비스에서 예산이 0원인 경우 전송하지 않도록 변경하였습니다.
=> [feat] 포트폴리오 추가 및 수정시 입력정보 변경

src/main/resources/member.yml, src/test/java/codesquad/fineants/spring/api/member/service/NicknameGeneratorTest.java
=> [fix] 회원 랜덤 닉네임 길이 변경

src/main/java/codesquad/fineants/domain/BaseEntity.java, src/main/java/codesquad/fineants/domain/notification/Notification.java, src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java, src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java, src/main/java/codesquad/fineants/spring/api/member/response/MemberNotification.java, src/main/java/codesquad/fineants/spring/api/member/response/MemberNotificationResponse.java, src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationService.java, src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java, src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
- 회원이 받은 알림 목록들을 조회하는 API를 구현하였습니다.
- 회원 알림 읽음
- 회원 알림 삭제
- 회원 알림 설저 수정
=> [feat] 회원 알림 목록 조회

build.gradle, src/main/java/codesquad/fineants/domain/BaseEntity.java, src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java, src/main/java/codesquad/fineants/domain/notification/Notification.java, src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java, src/main/java/codesquad/fineants/spring/api/errors/errorcode/FcmErrorCode.java, src/main/java/codesquad/fineants/spring/api/fcm/controller/FcmRestController.java, src/main/java/codesquad/fineants/spring/api/fcm/request/FcmRegisterRequest.java, src/main/java/codesquad/fineants/spring/api/fcm/response/FcmRegisterResponse.java, src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java, src/main/java/codesquad/fineants/spring/api/firebase/FirebaseMessagingService.java, src/main/java/codesquad/fineants/spring/api/firebase/NotificationMessage.java, src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java, src/main/java/codesquad/fineants/spring/api/member/response/MemberNotification.java, src/main/java/codesquad/fineants/spring/api/member/response/MemberNotificationResponse.java, src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationService.java, src/main/java/codesquad/fineants/spring/api/success/code/FcmSuccessCode.java, src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java, src/main/java/codesquad/fineants/spring/config/FirebaseConfig.java, src/test/java/codesquad/fineants/spring/api/fcm/controller/FcmRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/fcm/service/FcmServiceTest.java, src/test/java/codesquad/fineants/spring/api/firebase/FirebaseMessagingServiceTest.java, src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
- FCM 토큰 등록 API를 구현하였습니다.
- 토큰 등록 서비스시 FCM 서버에 검증용 메시지를 전송하여 유효하지 않은 토큰에 대해서는 400 응답을 하도록 구현하였습니다.
- api : POST /api/fcm/tokens
=> FCM 토큰 등록 구현

src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java, src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceService.java, src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java
- 기존 로컬 회원들도 알림 설정 수정시 데이터가 없어도 새로 생성하여 성공할 수 있도록 변경
=> [fix] 알림 설정 수정 API 문제 해결

src/main/java/codesquad/fineants/domain/oauth/support/AuthMember.java, src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java, src/main/java/codesquad/fineants/spring/auth/HasNotificationAuthorization.java, src/main/java/codesquad/fineants/spring/auth/HasNotificationAuthorizationAspect.java
- 회원 알림 관련 API 요청시 API 경로상의 memberId와 로그인한 회원의 memberId가 불일치하는 경우 403 응답을 하도록 구현하였습니다.
=> [feat] 회원 알림 권한 검사 AOP 추가

src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
=> [fix] 알림 모두 읽음 API에 권한 검사 AOP 추가

src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java, src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java, src/main/java/codesquad/fineants/spring/api/fcm/response/FcmDeleteResponse.java, src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java, src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationPreferenceRequest.java, src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceService.java, src/main/resources/db/mysql/init-schema.sql, src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java
- 회원 알람 설정 수정 API의 request body에 fcmTokenId 추가 (null 가능)
- 해당 API 요청시 모든 상태값이 false로 요청시 fcmTokenId에 해당하는 FCM 토큰 삭제
=> [fix] 회원 알람 설정 수정 스펙 변경

src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java, src/main/java/codesquad/fineants/domain/fcm_token/FcmToken.java, src/main/java/codesquad/fineants/spring/api/fcm/response/FcmRegisterResponse.java, src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java, src/test/java/codesquad/fineants/spring/api/fcm/service/FcmServiceTest.java
- FCM 토큰 등록 서비스시 기존에 이미 FCM 토큰이 존재하면 최신 활성화 시간을 갱신하는 것으로 로직을 변경하였습니다.
=> [feat] FCM 토큰 등록 로직 변경

src/main/java/codesquad/fineants/spring/api/member/response/ProfileResponse.java, src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java, src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java, src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
- 프로필 조회시 알림 설정이 더미 데이터에서 실제 회원의 알림 설정 데이터가 반영되도록 변경하였습니다.
- 종목 지정가 알림 특정 조회시 회원이 가지고 있지 않은 종목인 경우에는 빈 리스트를 반환합니다.
=> [fix] 프로필 조회 및 종목 지정가 알림 특정 조회 로직 수정

src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java, src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java, src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java, src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
- 포트폴리오 예산이 0원인 경우 포트폴리오 차트 조회 문제 해결
- 신규 회원가입시 계정 알림 설정을 모두 비활성화로 변경
=> #244 fix: 포트폴리오의 예산이 0원인 경우 포트폴리오 차트 문제 해결

src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java, src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java, src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingRepository.java, src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java, src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryRepository.java, src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java, src/main/java/codesquad/fineants/spring/api/notification/response/NotifyMessageItem.java, src/main/java/codesquad/fineants/spring/api/notification/response/NotifyPortfolioMessagesResponse.java, src/main/java/codesquad/fineants/spring/api/notification/service/NotificationService.java, src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java, src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java, src/main/java/codesquad/fineants/spring/api/purchase_history/event/NotificationEventListener.java, src/main/java/codesquad/fineants/spring/api/purchase_history/event/NotificationEventPublisher.java, src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryCreateRequest.java, src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryModifyRequest.java, src/test/java/codesquad/fineants/spring/api/fcm/service/FcmServiceTest.java, src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java, src/test/java/codesquad/fineants/spring/docs/notification/NotificationRestControllerDocsTest.java
- 매입 이력 이벤트 발생시 Notification 저장 문제를 해결하였습니다.
- 한 회원의 여러 디바이스에 알림을 발송하고 실제 알림 데이터는 1개만 저장되도록 변경하였습니다.
=> [fix] 매입 이력 이벤트에 따른 Notification 저장 문제 해결

src/main/java/codesquad/fineants/spring/api/notification/response/NotifyMessageItem.java, src/main/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationService.java, src/test/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationServiceTest.java
- notification 엔티티 데이터가 토큰이 여러개더라도 messageId를 기준으로 고유하게 1개만 저장하도록 저장
- 내용
=> [fix] 종목 지정가 알림 버그 수정

src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioHoldingRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioHoldingServiceTest.java, src/test/java/codesquad/fineants/spring/docs/holding/PortfolioHoldingRestControllerDocsTest.java
- 포트폴리오 상세 조회 API의 응답의 일부 프로퍼티명 변경하여 일관화
=> [fix] 포트폴리오 상세 조회 response property 변경

src/main/java/codesquad/fineants/spring/api/portfolio_notification_setting/response/PortfolioNotificationSettingSearchItem.java, src/test/java/codesquad/fineants/spring/api/portfolio_notification_setting/controller/PortfolioNotificationSettingRestControllerTest.java, src/test/java/codesquad/fineants/spring/api/portfolio_notification_setting/service/PortfolioNotificationSettingServiceTest.java, src/test/java/codesquad/fineants/spring/docs/portfolio/PortfolioNotificationSettingRestControllerDocsTest.java
- 포트폴리오 활성 알림 목록 조회의 응답에서 modifiedAt -> createdAt으로 변경
=> [fix] 포트폴리오 활성 목록 조회 응답 변경

src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java, src/main/java/codesquad/fineants/spring/api/common/errors/errorcode/PortfolioErrorCode.java, src/main/java/codesquad/fineants/spring/api/portfolio_notification/request/PortfolioNotificationUpdateRequest.java, src/main/java/codesquad/fineants/spring/api/portfolio_notification_setting/response/PortfolioNotificationSettingSearchItem.java, src/test/java/codesquad/fineants/spring/api/portfolio_notification/service/PortfolioNotificationServiceTest.java, src/test/java/codesquad/fineants/spring/docs/portfolio/PortfolioNotificationSettingRestControllerDocsTest.java
- 포트폴리오의 목표 수익금액이나 최대손실금액이 0원인 경우 해당 알림을 수정할 수 없도록 변경하였습니다.
- 포트폴리오 활성 알림 목록 조회(GET /portfolios/notification/settings) API에서 응답 프로퍼티에 isTargetGainSet, isMaxLossSet이 추가되었습니다.
=> [feat] 포트폴리 알림 수정

src/test/java/codesquad/fineants/docs/member/MemberRestControllerDocsTest.java, src/test/java/codesquad/fineants/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java
- 응답 프로퍼티로 값이 NULL이 올수있는 프로퍼티명의 설명을 수정하였습니다.
- 포트폴리오 종목 생성 API의 memo 리퀘스트 정보의 optional을 "Y"로 수정 (NULL 허용)
=> [docs] Rest Docs 설명 수정

src/main/java/codesquad/fineants/domain/kis/client/KisClient.java, src/main/java/codesquad/fineants/domain/kis/properties/OauthKisProperties.java, src/main/java/codesquad/fineants/domain/notification/service/NotificationService.java, src/main/java/codesquad/fineants/domain/stock_target_price/domain/dto/response/TargetPriceNotifyMessageItem.java, src/main/resources/application-test.yml, src/test/java/codesquad/fineants/domain/notification/service/NotificationServiceTest.java, src/test/java/codesquad/fineants/domain/portfolio_holding/service/PortfolioHoldingServiceTest.java
- 기존 알림을 발송한 다음에 성공한 알림들에 대해서만 알림 저장하는 방식에서, 알림을 저장한 다음에 알림을 발송하는 방식으로 변경하였습니다.
- 알림 발송을 실패하여도 알림 저장은 별개로 저장됩니다.
=> [fix] 알림 수정

src/main/java/codesquad/fineants/global/errors/errorcode/JwtErrorCode.java, src/main/java/codesquad/fineants/global/security/ajax/handler/AjaxAuthenticationSuccessHandler.java, src/main/java/codesquad/fineants/global/security/oauth/config/OauthSecurityConfig.java, src/main/java/codesquad/fineants/global/security/oauth/filter/JwtAuthenticationFilter.java, src/main/java/codesquad/fineants/global/security/oauth/handler/OAuth2SuccessHandler.java, src/main/java/codesquad/fineants/global/security/oauth/service/TokenService.java, src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java, src/test/java/codesquad/fineants/global/security/oauth/service/TokenServiceTest.java
- 액세스 토큰 및 리프레시 토큰 갱신 기능 구현
- oauth 로그인 성공시 최종 리다이렉트 쿼리 파라미터에 success=true 추가
=> [feat] 토큰 갱신 기능 구현 

src/main/java/codesquad/fineants/global/security/oauth/dto/OAuthAttribute.java
- 구글, 네이버, 카카오의 사용자가 최초 로그인시 프로필 동의하지 않은 경우 null로 저장하도록 수정
=> [fix] 프로필 사진 null 처리

src/main/java/codesquad/fineants/global/errors/errorcode/MemberErrorCode.java, src/main/java/codesquad/fineants/global/security/ajax/filter/AjaxLoginProcessingFilter.java, src/main/java/codesquad/fineants/global/security/ajax/handler/AjaxAuthenticationFailHandler.java, src/main/java/codesquad/fineants/global/security/ajax/provider/AjaxAuthenticationProvider.java, src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
- 일반 로그인 실패시 401이 아닌 400 응답이 나오도록 변경
=> [fix] 일반 로그인 실패 문제 해결

src/main/java/codesquad/fineants/domain/holding/domain/dto/response/PortfolioChartResponse.java, src/main/java/codesquad/fineants/domain/holding/domain/dto/response/PortfolioDetails.java, src/main/java/codesquad/fineants/domain/holding/service/PortfolioHoldingService.java, src/main/java/codesquad/fineants/domain/member/service/OauthMemberRedisService.java, src/main/java/codesquad/fineants/global/security/oauth/filter/JwtAuthenticationFilter.java, src/main/java/codesquad/fineants/global/security/oauth/service/TokenService.java, src/test/java/codesquad/fineants/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java, src/test/java/codesquad/fineants/domain/holding/controller/PortfolioHoldingRestControllerTest.java, src/test/java/codesquad/fineants/domain/holding/service/PortfolioHoldingServiceTest.java, src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
- API 응답에 portfolioDetails 프로퍼티 추가
- 액세스 토큰 갱신 테스트 코드 문제 해결
1. 레디스에 다른 테스트 케이스에 의해서 이미 로그아웃한 기록이 있어서 실패하였습니다.
2. 날짜 데이터 처리시 UTC 기준으로 변환되는 문제가 있었습니다.
=> [feat] 포트폴리오 차트 API 수정

.gitignore, build.gradle, src/docs/asciidoc/api/stock.adoc, src/main/java/codesquad/fineants/domain/stock/controller/StockRestController.java, src/main/java/codesquad/fineants/domain/stock/domain/dto/response/StockDataResponse.java, src/main/java/codesquad/fineants/domain/stock/domain/dto/response/StockSearchItem.java, src/main/java/codesquad/fineants/domain/stock/repository/StockQueryRepository.java, src/main/java/codesquad/fineants/domain/stock/service/StockService.java, src/main/java/codesquad/fineants/global/config/SpringConfig.java, src/test/java/codesquad/fineants/docs/stock/StockRestControllerDocsTest.java, src/test/java/codesquad/fineants/domain/stock/repository/StockQueryRepositoryTest.java
=> [feat] 종목 스크롤 검색

.github/workflows/ci.cd.release.yml, src/main/java/codesquad/fineants/global/init/SetupDataLoader.java
- 서버 실행시 배당금 초기화 호출 제거
- 시크릿 정보에서 s3 프로파일별 경로 오타 수정
=> [hotfix] 종목 및 배당일정 최신화 기능 버그

src/main/java/codesquad/fineants/domain/dividend/domain/reader/HolidayFileReader.java, src/main/java/codesquad/fineants/domain/holding/domain/entity/PortfolioHolding.java, src/main/java/codesquad/fineants/domain/kis/client/KisCurrentPrice.java, src/main/java/codesquad/fineants/domain/kis/domain/dto/response/KisDividendWrapper.java, src/main/java/codesquad/fineants/domain/kis/repository/CurrentPriceRedisRepository.java, src/main/java/codesquad/fineants/domain/kis/service/KisService.java, src/main/java/codesquad/fineants/domain/member/domain/entity/Member.java, src/main/java/codesquad/fineants/domain/notification/service/NotificationService.java, src/main/java/codesquad/fineants/domain/portfolio/domain/entity/Portfolio.java, src/main/java/codesquad/fineants/domain/purchasehistory/event/listener/PurchaseHistoryEventListener.java, src/main/java/codesquad/fineants/domain/purchasehistory/service/PurchaseHistoryService.java, src/main/java/codesquad/fineants/domain/stock/domain/entity/Stock.java, src/main/java/codesquad/fineants/domain/stock/service/StockAndDividendManager.java, src/main/java/codesquad/fineants/domain/stock_target_price/domain/entity/StockTargetPrice.java, src/main/java/codesquad/fineants/domain/stock_target_price/domain/entity/TargetPriceNotification.java, src/main/java/codesquad/fineants/domain/watchlist/domain/entity/WatchList.java, src/main/java/codesquad/fineants/global/common/delay/DelayManager.java, src/main/java/codesquad/fineants/global/config/SpringConfig.java, src/main/java/codesquad/fineants/global/init/SetupDataLoader.java, src/test/java/codesquad/fineants/domain/kis/service/KisServiceTest.java, src/test/java/codesquad/fineants/domain/notification/event/listener/PurchaseHistoryEventListenerTest.java, src/test/java/codesquad/fineants/domain/notification/service/NotificationServiceTest.java, src/test/java/codesquad/fineants/domain/purchasehistory/service/PurchaseHistoryServiceTest.java, src/test/java/codesquad/fineants/domain/stock/service/StockServiceTest.java
- 매입 이력 이벤트에 따른 알람 서비스에서 삭제된 매입 이력이 같이 조회되는 문제를 해결하였습니다.
- 주식 현재가 갱신시 Flux를 이용하도록 변경 (리팩토링 진행중)
=> [fix] 매입 이력 알람 리스너 문제 해결

src/main/java/codesquad/fineants/domain/kis/repository/CurrentPriceRedisRepository.java, src/main/java/codesquad/fineants/domain/kis/service/KisService.java
=> [fix] 현재가 조회 수정

src/main/java/co/fineants/api/domain/gainhistory/domain/entity/PortfolioGainHistory.java, src/main/java/co/fineants/api/domain/gainhistory/service/PortfolioGainHistoryService.java, src/main/java/co/fineants/api/domain/portfolio/controller/DashboardRestController.java, src/main/java/co/fineants/api/domain/portfolio/service/DashboardService.java, src/main/java/co/fineants/api/global/config/CacheConfig.java
- LineChart API에 캐시 추가
- TTL : 24 hour
5000건의 포트폴리오를 계산하는 라인 차트를 조회하는 작업에 캐시 적용전/후의 성능 테스트 결과
평균 TPS : { 0.8 } → { 624.6 }
- 약 780.75배 개선
Peek TPS : { 5.0 } → { 780.5 }
- 약 156.1배 개선
Mean Test Time : { 18,157.13ms } → { 14.53ms }
- 약 1249.63배 단축
Executed Tests : { 30 } → { 35,039 }
- 약 1167.96배 개선
=> [feat] LineChart API 개선

src/main/java/co/fineants/api/domain/holding/domain/entity/PortfolioHolding.java, src/main/java/co/fineants/api/domain/portfolio/domain/dto/request/PortfolioCreateRequest.java, src/main/java/co/fineants/api/domain/portfolio/domain/dto/request/PortfolioModifyRequest.java, src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java, src/main/java/co/fineants/api/domain/portfolio/domain/entity/PortfolioDetail.java, src/main/java/co/fineants/api/domain/portfolio/repository/PortfolioRepository.java, src/main/java/co/fineants/api/domain/portfolio/service/PortFolioService.java, src/test/java/co/fineants/AbstractContainerBaseTest.java, src/test/java/co/fineants/api/docs/RestDocsSupport.java, src/test/java/co/fineants/api/domain/holding/domain/entity/PortfolioHoldingTest.java, src/test/java/co/fineants/api/domain/portfolio/domain/entity/PortfolioDetailTest.java, src/test/java/co/fineants/api/domain/portfolio/domain/entity/PortfolioTest.java, src/test/java/co/fineants/api/domain/portfolio/repository/PortfolioRepositoryTest.java, src/test/java/co/fineants/api/domain/portfolio/service/PortFolioServiceTest.java, src/test/java/co/fineants/support/controller/ControllerTestSupport.java
- name, securitiesFirm 필드를 임베딩
- 엔티티 클래스의 생성자 및 정적 메서드 생성자 줄이기
- ToString 재정의
- 연관관계 편의 메서드 개선
- budget, targetGain, maximumLoss를 하나로 묶은 임베딩 클래스 추가
=> [refactor] 포트폴리오 엔티티 개선

src/main/java/co/fineants/api/global/security/factory/CookieDomainProvider.java, src/main/java/co/fineants/api/global/security/factory/DeployCookieDomainProvider.java, src/main/java/co/fineants/api/global/security/factory/LocalCookieDomainProvider.java, src/main/java/co/fineants/api/global/security/factory/TokenFactory.java
- 배포환경에서 도메인 이름 .fineants.co를 제공하는 provider 구현
=> [feat] CookieDomainProvider 인터페이스 선언 및 구현클래스 추가

src/main/java/co/fineants/api/domain/dividend/domain/entity/DividendDates.java, src/main/java/co/fineants/api/domain/dividend/domain/entity/StockDividend.java, src/main/java/co/fineants/api/domain/holding/domain/chart/DividendChart.java, src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioDividendChartItem.java, src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioHoldingDetailItem.java, src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioHoldingItem.java, src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioHoldingRealTimeItem.java, src/main/java/co/fineants/api/domain/holding/domain/entity/PortfolioHolding.java, src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioHoldingDetailFactory.java, src/main/java/co/fineants/api/domain/holding/repository/PortfolioHoldingRepository.java, src/main/java/co/fineants/api/domain/holding/service/PortfolioHoldingService.java, src/main/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculator.java, src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java, src/main/java/co/fineants/api/domain/purchasehistory/domain/entity/PurchaseHistory.java, src/main/java/co/fineants/api/domain/purchasehistory/service/PurchaseHistoryService.java, src/main/java/co/fineants/api/domain/stock/domain/dto/response/StockResponse.java, src/main/java/co/fineants/api/domain/stock/domain/entity/Stock.java, src/test/java/co/fineants/api/domain/holding/domain/entity/PortfolioHoldingTest.java, src/test/java/co/fineants/api/domain/holding/service/PortfolioHoldingServiceTest.java, src/test/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculatorTest.java, src/test/java/co/fineants/api/domain/portfolio/service/DashboardServiceTest.java, src/test/java/co/fineants/api/domain/portfolio/service/PortFolioServiceTest.java, src/test/java/co/fineants/api/domain/purchasehistory/domain/entity/PurchaseHistoryTest.java, src/test/java/co/fineants/api/domain/purchasehistory/service/PurchaseHistoryServiceTest.java
- 포트폴리오 종목의 계산 로직을 객체지향적으로 PortfolioCalculator로 이전하도록 개선
- 남은 계산 메서드들을 계산기로 이전
- javadoc 추가
- 계산 메서드들에 대한 테스트 코드 작성
=> [refactor] 포트폴리오 종목 및 계산기 개선

src/test/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculatorTest.java
- PortfolioCalculator의 calSectorChartBy 메서드의 테스트 순서 변경
=> [test] 테스트 순서 변경

src/main/java/co/fineants/api/domain/portfolio/controller/PortFolioRestController.java, src/main/java/co/fineants/api/domain/portfolio/domain/dto/response/PortfolioNameItem.java, src/main/java/co/fineants/api/domain/portfolio/domain/dto/response/PortfolioNameResponse.java, src/main/java/co/fineants/api/domain/portfolio/service/PortFolioService.java, src/main/java/co/fineants/api/global/config/CacheConfig.java, src/main/java/co/fineants/api/global/config/jackson/JacksonConfig.java, src/test/java/co/fineants/api/domain/portfolio/service/PortFolioServiceTest.java, src/test/java/co/fineants/api/global/config/jackson/CacheObjectMapperTest.java
- 포트폴리오 이름 목록 API에 캐시 추가
- 평균 TPS : { 40.8 } → { 56.4 }
- 약 1.38배 개선
- Peek TPS : { 48.5 } → { 65.5 }
- 약 1.35배 개선
- Mean Test Time : { 236.94ms } → { 176.23ms }
- 약 1.34배 단축
- Executed Tests : { 2,382 } → { 3,167 }
- 약 1.32배 개선
=> [feat] 포트폴리오 이름 목록 API에 캐시 추가

src/main/java/co/fineants/api/domain/purchasehistory/service/PurchaseHistoryService.java, src/test/java/co/fineants/api/domain/purchasehistory/service/PurchaseHistoryServiceTest.java
- 매입 이력 추가 서비스에서 포트폴리오 종목의 매입 이력 리스트에 직전에 추가한 매입 이력 추가 코드를 제거함
- 제거 이유는 이벤트 리스너가 비동기 및 `@TransactionalEventListener` 설정으로 인한 불필요해져서입니다.
- 매입 이력 추가 서비스 후 알림이 저장되었는지 테스트 추가
=> [refactor] 매입 이력 추가 서비스 수정

build.gradle, src/jmh/java/co/fineants/api/domain/portfolio/service/PortfolioCacheServiceBenchMark.java
- JMH 라이브러리 추가
- 포트폴리오 캐시 서비스의 메서드 성능 측정 추가
캐싱 이전 측정 결과
캐싱 이후 측정 결과
수치 변화
- 평균 시간 : { 5.029 ms } → { 0.448 }
- 약 11.22배 개선
=> [performance] JMH 추가 및 성능 측정

src/test/java/co/fineants/api/infra/s3/service/AmazonS3StockServiceTest.java
- CI-CD 과정에서 테스트 실패 해결
- 원인: 테스트 실행 순서에서 csv 파일에 종목 저장 테스트 후에 다른 테스트 실행시 개수가 맞지 않아서
- 해결방법: csv 파일에 종목 저장하는 테스트에 테스트가 끝나고 롤백하는 코드(다시 종목을 작성하는)를 추가하여 해결
=> [fix] 테스트 실패 해결

src/main/java/co/fineants/api/domain/BaseEntity.java, src/main/java/co/fineants/api/domain/gainhistory/domain/entity/PortfolioGainHistory.java, src/main/java/co/fineants/api/domain/gainhistory/repository/PortfolioGainHistoryRepository.java, src/main/java/co/fineants/api/domain/gainhistory/service/PortfolioGainHistoryService.java, src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioDetailFactory.java, src/main/java/co/fineants/api/domain/member/service/MemberService.java, src/main/java/co/fineants/api/domain/portfolio/service/PortFolioService.java, src/test/java/co/fineants/api/domain/gainhistory/repository/PortfolioGainHistoryRepositoryTest.java
- 300만건의 데이터가 존재하는 상태에서 쿼리에 대한 성능을 개선
- 데이터베이스 마이그레이션을 학습하여 복합 인덱스를 추가하는 스크립트 작성
=> [refactor] 포트폴리오 손익 내역 쿼리 개선

src/docs/asciidoc/api/portfolio.adoc, src/main/java/co/fineants/api/domain/portfolio/controller/PortFolioRestController.java, src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java, src/main/java/co/fineants/api/domain/portfolio/repository/PortfolioRepository.java, src/main/java/co/fineants/api/domain/portfolio/service/PortFolioService.java, src/main/java/co/fineants/api/global/common/page/CustomPageRequest.java, src/main/java/co/fineants/api/global/common/page/CustomPageResponse.java, src/main/java/co/fineants/api/global/config/FlywayConfig.java, src/main/resources/application-local.yml, src/main/resources/application-test.yml, src/main/resources/db/mysql/migration/V4__add_index_portfolio.sql, src/test/java/co/fineants/api/docs/portfolio/PortfolioRestControllerDocsTest.java, src/test/java/co/fineants/api/domain/portfolio/repository/PortfolioRepositoryTest.java, src/test/java/co/fineants/api/domain/portfolio/service/PortFolioServiceTest.java
- 포트폴리오 이름 목록 API 조회시 페이징을 적용하였습니다.
- 포트폴리오 테이블에 복합 인덱스를 추가하여 쿼리 성능을 개선하였습니다.
- 300만건의 포트폴리오 데이터에 대해서 포트폴리오 이름 목록 API 요청시 기존 3970ms -> 948ms로 약 4.18배 개선되었습니다.
- 페이징 처리하는 서비스 메서드에 캐싱 추가
- 다른 포트폴리오 쿼리 개선
=> [feat] 포트폴리오 쿼리 성능 개선

src/main/java/co/fineants/api/domain/holding/config/PortfolioStreamerConfig.java, src/main/java/co/fineants/api/domain/holding/config/PortfolioStreamerFactoryConfig.java, src/main/java/co/fineants/api/domain/holding/config/SseEmitterFactoryConfig.java, src/main/java/co/fineants/api/domain/holding/controller/PortfolioHoldingRestController.java, src/main/java/co/fineants/api/domain/holding/domain/factory/AlwaysOpenPortfolioStreamerFactory.java, src/main/java/co/fineants/api/domain/holding/domain/factory/DefaultUuidGenerator.java, src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioSseEmitterFactory.java, src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioSseEventBuilderFactory.java, src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioStreamMessageConsumerFactory.java, src/main/java/co/fineants/api/domain/holding/domain/factory/SseEventBuilderFactory.java, src/main/java/co/fineants/api/domain/holding/domain/factory/UuidGenerator.java, src/main/java/co/fineants/api/domain/holding/service/sender/StreamCompleteMessageSender.java, src/main/java/co/fineants/api/domain/holding/service/sender/StreamContinuesMessageSender.java, src/main/java/co/fineants/api/domain/holding/service/sender/StreamSseMessageSender.java, src/main/java/co/fineants/api/domain/holding/service/streamer/AlwaysOpenPortfolioStreamer.java, src/main/java/co/fineants/api/domain/holding/service/streamer/FluxIntervalPortfolioStreamer.java, src/main/java/co/fineants/api/domain/holding/service/streamer/PortfolioStreamer.java, src/test/java/co/fineants/api/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java, src/test/java/co/fineants/api/domain/holding/controller/PortfolioHoldingRestControllerTest.java, src/test/java/co/fineants/api/domain/holding/domain/factory/PortfolioSseEmitterFactoryTest.java, src/test/java/co/fineants/api/domain/holding/domain/factory/PortfolioSseEventBuilderFactoryTest.java, src/test/java/co/fineants/api/domain/holding/service/sender/StreamCompleteMessageSenderTest.java, src/test/java/co/fineants/api/domain/holding/service/sender/StreamContinuesMessageSenderTest.java, src/test/java/co/fineants/api/domain/holding/service/streamer/AlwaysOpenPortfolioStreamerTest.java, src/test/java/co/fineants/config/ControllerTestConfig.java
- SseEventBuilder 객체를 생성하는 중복 로직을 제거하였습니다.
- 주식장 시간에 상관없이 포트폴리오의 수익율을 스트리밍하는 구현체를 확장하였습니다. 해당 구현체를 생성한 이유는 로컬 개발 환경에서 SSE 포트폴리오 수익율 테스트를 하기 위함
- SseEventBuilderFactory 인터페이스를 생성하여 객체 생성 중복 로직을 제거하였습니다.
- 해당 리팩토링으로 인하여 추가된 클래스들의 단위 테스트 구현
=> [refactor] SseEventBuilder 중복 개선

src/main/java/co/fineants/api/domain/kis/scheduler/KisProductionScheduler.java
- `@SchedulerLock` 애노테이션 옵션의 `lockAtLeastFor=6s`, `lockAtMostFor=12s`로 수정
- `lockAtLeastFor=6s` 설정 이유
- 작업이 일찍 끝나도 다음 스케줄 실행 전까지 락을 유지함
- 스케줄러가 빠르게 재호출되는 것을 막아줌
- 여러 인스턴스에서 추가로 중복 실행되는 상황을 차단
- `lockAtMostFor=12s` 설정 이유
- 현재 배포 서버 기준으로 36개의 종목의 현재가를 갱신하는데 약 6초정도 소요됨
- 실행시간 * 2로 설정하여 중복 실행하는 상황을 차단시킴
=> [refactor] 스케줄러 락 애노테이션 옵션 수정

src/main/java/co/fineants/api/domain/holding/service/PortfolioHoldingService.java, src/test/java/co/fineants/api/domain/holding/service/PortfolioHoldingFacadeTest.java, src/test/java/co/fineants/api/domain/holding/service/PortfolioHoldingServiceTest.java
- 기존 PortfolioHoldingService.createPortfolioHolding 메서드 및 관련 테스트 제거
- PortfolioHoldingFacade.createPortfolioHolding 메서드 대상 테스트 추가
=> [refactor] 기존 포트폴리오 종목 생성 메서드 수정

src/main/java/co/fineants/api/domain/dividend/config/StockDividendConfig.java, src/main/java/co/fineants/api/domain/dividend/domain/parser/StockDividendCsvLineParser.java, src/main/java/co/fineants/api/domain/dividend/domain/parser/StockDividendCsvParser.java, src/main/java/co/fineants/api/infra/s3/config/GoogleCloudStorageConfig.java, src/main/java/co/fineants/api/infra/s3/config/S3Config.java, src/main/java/co/fineants/api/infra/s3/service/imple/AmazonS3FetchDividendService.java, src/main/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageDeleteDividendService.java, src/main/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageFetchDividendService.java, src/main/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageRemoteFileFetcher.java, src/main/java/co/fineants/api/infra/s3/service/imple/StockDividendCsvParser.java, src/test/java/co/fineants/TestDataFactory.java, src/test/java/co/fineants/api/infra/s3/service/imple/AmazonS3FetchDividendServiceTest.java, src/test/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageDeleteDividendServiceTest.java, src/test/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageFetchDividendServiceTest.java, src/test/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageWriteDividendServiceTest.java
- 종목 배당금 csv 파일 읽기 서비스에 대한 테스트 코드 구현
- 배당금 csv 파일의 파싱하는 코드를 추출하여 클래스로 구현
- 종목 배당금 csv 파일 삭제 서비스 구현(GCP 버전)
- 종목 csv 파일에 대한 읽기/쓰기/삭제 서비스에 대한 구현체 확장 구현
=> [feat] 종복 배당금 csv 파일의 읽기/삭제 서비스 기능 및 테스트 구현
