fine-ants/FineAnts-was

- .gitignore
- build.gradle
- src/main/java/codesquad/fineants/domain/jwt/Jwt.java
- src/main/java/codesquad/fineants/domain/oauth/client/DecodedIdTokenPayload.java
- src/main/java/codesquad/fineants/domain/oauth/client/KakaoOauthClient.java
- src/main/java/codesquad/fineants/domain/oauth/client/NaverOauthClient.java
- src/main/java/codesquad/fineants/domain/oauth/client/OauthClient.java
- src/main/java/codesquad/fineants/domain/oauth/properties/OauthProperties.java
- src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
- src/main/java/codesquad/fineants/spring/aop/SimpleLogAop.java
- src/main/java/codesquad/fineants/spring/api/errors/errorcode/JwkErrorCode.java
- src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/service/JwkProviderSingleton.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/test/java/codesquad/fineants/domain/oauth/client/KakaoOauthClientTest.java
- src/test/java/codesquad/fineants/domain/oauth/client/OauthClientTest.java
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
- 카카오 소셜 로그인은 PKCE + OpenIDConnect 방식으로 수행하도록 하고 네이버는 일반적인 accessToken으로 프로필을 가져오도록 개선
- 테스트 코드 추가
> [feat] 네이버 소셜 로그인 개선

- src/main/java/codesquad/fineants/domain/oauth/client/AuthorizationCodeRandomGenerator.java
- src/main/java/codesquad/fineants/domain/oauth/repository/InMemoryOauthClientRepository.java
- src/main/java/codesquad/fineants/domain/oauth/repository/OauthClientRepository.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/member/service/WebClientWrapper.java
> [feat] final 키워드 추가

- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
- /api/auth/:provider/url -> /api/auth/:provider/authUrl 변경
> [fix] 인가 코드 URL 생성의 URL 변경

- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
> [fix] 네이버 로그인 문제로 인한 로그 추가

- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryService.java
- src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationService.java
- src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
- scheduledPortfolioGainHistory 메소드에 "@Transactional" 애노테이션을 붙여서 데이터베이스에 반영하도록 함
> [fix] 포트폴리오 수익 히스토리 생성 메소드에 @Transactional 추가

- Dockerfile
- build.gradle
- docker-compose-analyze.yml
- src/main/resources/application.yml
- jmeter를 이용하여 성능 측정을 하기 위해서 프로파일 설정에 analyze을 추가하였습니다.
- analyze 프로파일 추가 이유는 로컬 개발 환경에서 성능 측정시 실행 환경은 docker 위에 spring, db, redis 컨테이너를 실행합니다. 그런데 local 프로파로 실행시 db 연결설정이 맞지 않아서 실행할 수 없기 때문입니다. 그래서 별도의 analyze라는 프로파일을 추가하여 실행할 수 있도록 추가하였습니다.
> [docs] analyze profile 추가

- src/main/java/codesquad/fineants/domain/oauth/client/DecodedIdTokenPayload.java
- src/test/java/codesquad/fineants/domain/oauth/client/OauthClientTest.java
- nonce 검증 테스트에서 validatePayload 메소드로 범위를 줄여서 테스트 코드를 작성하였습니다.
- DecodedIdTokenPayload 클래스의 exp 타입이 명세서와 달라 Integer로 수정하였습니다.
> [feat] OauthClientTest 테스트 코드 실패 해결

- src/main/java/codesquad/fineants/spring/config/WebConfig.java
- src/main/java/codesquad/fineants/spring/converter/SseEventStreamMessageConverter.java
- 스프링에서 text/event-stream 데이터를 처리하여 json으로 변환하여 응답하기 위해서 SseEventStreamMessageConverter 객체를 구현하였습니다.
> [feat] SseEventStreamMessageConverter 구현

- src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
- SSE 테스트시 테스트가 바로 완료될 수 있도록 StockMarketChecker 객체의 모킹 설정을 변경하였습니다.
> [fix] 테스트 코드 모킹 설정 변경

- src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
- src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
- src/main/java/codesquad/fineants/domain/stock/Stock.java
- src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
> [fix] calculate current year dividend

- build.gradle
- src/main/java/codesquad/fineants/domain/member/MemberRepository.java
- src/main/java/codesquad/fineants/spring/api/S3/service/AmazonS3Service.java
- src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/request/LoginRequest.java
- src/main/java/codesquad/fineants/spring/api/member/request/SignUpRequest.java
- src/main/java/codesquad/fineants/spring/api/member/request/VerifyEmailRequest.java
- src/main/java/codesquad/fineants/spring/api/member/response/LoginResponse.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/member/service/OauthMemberRedisService.java
- src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
- src/main/java/codesquad/fineants/spring/config/AwsS3Config.java
- src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
- 회원가입
- 로그인
- 프로필 이미지 업로드 기능
- 인증 코드 전송 기능
- 회원가입 입력 검증
- 닉네임 중복 검사
- 이메일 중복 검사
> [feat] 일반 회원가입, 로그인 기능 구현

- src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfoliosDeleteRequest.java
> [fix] add default constructor

- build.gradle
- src/main/java/codesquad/fineants/domain/member/Member.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/config/EncoderConfig.java
> [feat] 비밀번호 암호화, 프로필 사진 수정

- src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
> [bug] 라인 차트 조회시 데이터 정렬

- src/test/java/codesquad/fineants/domain/oauth/client/KakaoOauthClientTest.java
- application-secret.yml 파일의 redirect-uri 변경
- 테스트 코드 수정
> [docs] redirect uri 변경

- src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
- src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
- src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
- src/test/java/codesquad/fineants/domain/oauth/client/KakaoOauthClientTest.java
- src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
- 포트폴리오 단일 삭제시 포트폴리오 삭제전에 "포트폴리오 손익내역"을 제거하도록 추가
- 포트폴리오 테스트 코드 정리
> [fix] 포트폴리오 단일 삭제 문제 해결

- docker-compose-dev.yml
- docker-compose-dev.yml 파일에 CloudWatch 정보 추가
> [docs] CloudWatch 정보 추가

- src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
- 포트폴리오 상세 조회시 currentValuation 프로퍼티 추가
- api : {{url}}/api/portfolio/:portfolioId/holdings
> [fix] 포트폴리오 상세 조회시 currentValuation 프로퍼티 추가

- src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
- src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
- src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
- src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
- 현금 부족시 매입 이력 추가가 실패하는 로직을 구현했습니다.
- 실패를 검증하기 위한 Controller 테스트와 Service 테스트를 작성했습니다.
> [fix] validate portfolio total investment

- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
- Stock 엔티티에 Market 필드를 추가했습니다.
> [test] add market to stock entity

- src/main/java/codesquad/fineants/domain/watch_stock/WatchStockRepository.java
- src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
- src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
- src/main/java/codesquad/fineants/spring/api/watch_list/request/CreateWatchStockRequest.java
- src/main/java/codesquad/fineants/spring/api/watch_list/request/DeleteWatchListsRequests.java
- src/main/java/codesquad/fineants/spring/api/watch_list/request/DeleteWatchStocksRequest.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
- watchlist api의 변경된 형식대로 코드를 수정했습니다.
> [feat] watchlist request 변경

- src/main/java/codesquad/fineants/domain/jwt/JwtProvider.java
- 액세스 토큰 추출시 만료되는 경우 403 응답하도록 변경
- 시크릿 파일에 액세스 토큰 만료시간 5분으로 변경
> [fix] 오타 수정

- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- 일반 로그인 서비스 수행시 회원을 탐색할때 provider를 "local"로 전달하도록 수정하였습니다.
> [fix] 일반 로그인 오타 수정

- src/main/java/codesquad/fineants/domain/watch_list/WatchList.java
- src/main/java/codesquad/fineants/domain/watch_stock/WatchStock.java
- WatchList와 WatchStock의 ID 생성 전략을 변경했습니다.
> [fix] watchlist create

- src/main/java/codesquad/fineants/domain/stock/Stock.java
- src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
- src/main/java/codesquad/fineants/spring/api/kis/manager/LastDayClosingPriceManager.java
- null일 때 Exception 던지는 것을 제거하고 null을 반환하도록 수정했습니다.
> [fix] price null

- src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/request/VerifCodeRequest.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
> [refactor] 인증코드 확인 api 분리

- src/main/java/codesquad/fineants/domain/member/Member.java
- src/main/java/codesquad/fineants/spring/api/S3/service/AmazonS3Service.java
- src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/request/ModifyPasswordRequest.java
- src/main/java/codesquad/fineants/spring/api/member/request/ProfileChangeRequest.java
- src/main/java/codesquad/fineants/spring/api/member/response/ProfileChangeResponse.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
> [feat] 계정 API, 프로필 정보 변경 API 구현

- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- 불필요한 accessToken 매개변수를 제거하였습니다.
> [fix] 계정 삭제 문제 해결

- src/main/java/codesquad/fineants/domain/member/MemberRepository.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- 비밀번호 변경 서비스에서 실제 데이터베이스에 반영하도록 구현
> [fix] 비밀번호 변경 문제 해결

- src/test/java/codesquad/fineants/spring/api/dashboard/DashboardServiceTest.java
- src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
- src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
- 대시보드 오버뷰 테스트에서 레디스를 모킹처리하여 테스트 실패를 해결하였습니다.
> [fix] 대시보드 서비스 클래스 테스트 코드 문제

- src/main/java/codesquad/fineants/domain/watch_list/WatchList.java
- src/main/java/codesquad/fineants/domain/watch_list/WatchListRepository.java
- src/main/java/codesquad/fineants/spring/api/success/code/WatchListSuccessCode.java
- src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
- src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
- src/main/java/codesquad/fineants/spring/api/watch_list/request/ChangeWatchListNameRequest.java
- src/main/java/codesquad/fineants/spring/api/watch_list/response/WatchListHasStockResponse.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
- GET /api/watchlists/has-stock/:tickerSymbol
- PUT /api/watchlists/:watchListId
> [feat] change watchlist name

- src/main/java/codesquad/fineants/domain/stock/Stock.java
- src/main/java/codesquad/fineants/spring/api/stock/StockRestController.java
- src/main/java/codesquad/fineants/spring/api/stock/StockService.java
- src/main/java/codesquad/fineants/spring/api/stock/response/GetStockResponse.java
- src/main/java/codesquad/fineants/spring/api/stock/response/StockResponse.java
- src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
- src/test/java/codesquad/fineants/spring/api/stock/StockRestControllerTest.java
- 종목 상세정보 조회 API를 구현했습니다.
- 종목 상세정보 조회 API Controller test를 작성했습니다.
> [feat] stock detail

- src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
> [fix] stockExists Endpoint

- src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
- src/main/java/codesquad/fineants/spring/api/member/response/ProfileResponse.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
> [feat] 프로필 정보 조회

- src/main/java/codesquad/fineants/domain/fcm_token/FcmToken.java
- src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java
- src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
- src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPrice.java
- src/main/resources/db/mysql/init-schema.sql
- 알림에 필요한 JPA 엔티티를 정의했습니다.
- member_id를 pk를 뒀을 때, Member를 serialization해줘야 하는 문제가 있어 id 필드를 추가하고 이를 pk로 설정했습니다.
- naming과 자료형 등을 검토 부탁드립니다.
- resource 하위에 있는 ddl은 테이블 확정 후에 업데이트 하겠습니다.
> [feat] notification entity

- build.gradle
- src/main/java/codesquad/fineants/spring/api/firebase/FirebaseMessagingService.java
- src/main/java/codesquad/fineants/spring/api/firebase/NotificationMessage.java
- src/main/java/codesquad/fineants/spring/config/FirebaseConfig.java
- src/test/java/codesquad/fineants/spring/api/firebase/FirebaseMessagingServiceTest.java
- FCM 스프링 빈 설정 클래스 구현
- 알림 메시지를 전송하는 간단한 서비스 메소드 구현
- 알림 메시지 전송 테스트 코드 추가
> [feat] FCM 관련 스프링 빈 구현

- src/main/java/codesquad/fineants/domain/notification/Notification.java
- src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java
- src/main/java/codesquad/fineants/spring/api/errors/errorcode/NotificationErrorCode.java
- src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
- src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationAllDeleteRequest.java
- src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationAllReadRequest.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationService.java
- src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
- src/main/resources/db/mysql/init-schema.sql
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
> [feat] 회원 알림 관련 API 구현

- src/main/resources/db/mysql/init-schema.sql
- init-schema.sql 파일에서 FcmToken 테이블 생성 쿼리 오타를 수정하였습니다.
- pk 컬럼에 auto_increment 추가
> [fix] FcmToken 테이블 생성 쿼리 오타 수정

- src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
- src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
- src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
- src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
- src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
- 포트폴리오 종목 조회시 N+1 문제 해결 및 쿼리 호출수 감소
- 기존 7번 호출을 3번 호출로 감소
> [Refactor] 포트폴리오 종목 조회 리팩토링

- src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPrice.java
- src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
- src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
- src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
- src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
- src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationDeleteRequest.java
- src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationDeleteResponse.java
- src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
- src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
- 종목 지정가 알림 단일 및 전체 제거 API를 구현하였습니다.
> [feat] 종목 지정가 알림 제거 API 구현

- src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
- src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
- src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationCreateRequest.java
- src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationSingleDeleteRequest.java
- src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
> [fix] 종목 지정가 알림 경로 변경

- src/main/java/codesquad/fineants/spring/api/dashboard/response/OverviewResponse.java
- src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
- 대시보드 오버뷰 API의 리스폰스 바디에 totalGain 프로퍼티를 추가하였습니다.
> [fix] 대시보드 오버뷰 리스폰스 바디에 totalGain 추가

- src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java
- FCM 토큰 등록시 유니크한지 검증하는 검증문을 제거하였습니다.
> [fix] 검증문 제거

- docker-compose.yml
- src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
- src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationSearchItem.java
- src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
- 종목 지정가 알림 목록 조회 API를 구현하였습니다.
> [feat] 종목 지정가 알림 목록 조회 API 구현

- src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
- src/main/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingRestController.java
- src/main/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingService.java
- src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioNotificationSettingSearchItem.java
- src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioNotificationSettingSearchResponse.java
- src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
- src/test/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingServiceTest.java
> [feat] 포트폴리오 활성 알림 목록 조회 API 구현

- .github/workflows/cicd.yml
- github ci/cd 과정에서 test를 수행할 수 있도록 단계를 추가하였습니다.
> [docs] ci 수행시 test 추가

- src/docs/asciidoc/api/dashboard.adoc
- src/docs/asciidoc/api/holding.adoc
- src/docs/asciidoc/api/member.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java
- src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java
- src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreferenceRepository.java
- src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
- src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
- src/main/java/codesquad/fineants/domain/target_price_notification/TargetPriceNotificationRepository.java
- src/main/java/codesquad/fineants/spring/api/dashboard/controller/DashboardRestController.java
- src/main/java/codesquad/fineants/spring/api/dashboard/response/OverviewResponse.java
- src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
- src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java
- src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
- src/main/java/codesquad/fineants/spring/api/watch_list/event/WatchStockEvent.java
- src/main/java/codesquad/fineants/spring/api/watch_list/event/listener/WatchStockEventListener.java
- src/main/java/codesquad/fineants/spring/api/watch_list/event/publisher/WatchStockEventPublisher.java
- src/test/java/codesquad/fineants/spring/api/dashboard/service/DashboardServiceTest.java
- src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
- src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
- src/test/java/codesquad/fineants/spring/docs/RestDocsSupport.java
- src/test/java/codesquad/fineants/spring/docs/dashboard/DashboardRestControllerDocsTest.java
- src/test/java/codesquad/fineants/spring/docs/holding/PortfolioStockRestControllerDocsTest.java
- src/test/java/codesquad/fineants/spring/member/MemberRestControllerDocsTest.java
- 연배당률에 소수점 2잘 실수 포함
- 대시보드 오버뷰 조회 문제 해결
- WatchStock 추가시 현재가 갱신하도록 이벤트 추가
- 계정 삭제 문제 해결
> [fix] qa 버그 문제 해결

- src/docs/asciidoc/api/member.adoc
- src/docs/asciidoc/api/portfolio.adoc
- src/main/java/codesquad/fineants/spring/api/member/response/OauthMemberRefreshResponse.java
- src/main/java/codesquad/fineants/spring/api/member/response/OauthSaveUrlResponse.java
- src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
- src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
- src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
- src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
- src/test/java/codesquad/fineants/spring/api/stock/StockRestControllerTest.java
- src/test/java/codesquad/fineants/spring/docs/member/MemberRestControllerDocsTest.java
- src/test/java/codesquad/fineants/spring/docs/portfolio/PortfolioRestControllerDocsTest.java
- 회원 및 포트폴리오 API에 대한 Rest Docs API 추가
> [docs] Rest Docs API 추가

- src/docs/asciidoc/api/notification.adoc
- src/test/java/codesquad/fineants/spring/docs/member/MemberRestControllerDocsTest.java
> [docs] notification adoc 수정

- src/docs/asciidoc/api/notification.adoc
- src/test/java/codesquad/fineants/spring/docs/member/MemberRestControllerDocsTest.java
> [docs] Rest Docs 테스트 실패 해결

- src/main/java/codesquad/fineants/domain/fcm_token/FcmToken.java
- src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
- src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
- src/main/java/codesquad/fineants/spring/api/kis/manager/LastDayClosingPriceManager.java
- src/main/java/codesquad/fineants/spring/api/kis/service/KisService.java
- src/main/java/codesquad/fineants/spring/api/notification/response/NotifyMessageItem.java
- src/main/java/codesquad/fineants/spring/api/notification/service/NotificationService.java
- src/main/java/codesquad/fineants/spring/api/stock_target_price/manager/TargetPriceNotificationSentManager.java
- src/main/java/codesquad/fineants/spring/api/stock_target_price/request/StockTargetPriceNotificationCreateRequest.java
- src/main/java/codesquad/fineants/spring/api/stock_target_price/response/TargetPriceNotificationSendItem.java
- src/main/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationService.java
- src/test/java/codesquad/fineants/spring/api/kis/service/KisServiceTest.java
- src/test/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationServiceTest.java
- src/test/java/codesquad/fineants/spring/docs/notification/NotificationRestControllerDocsTest.java
- src/test/java/codesquad/fineants/spring/docs/stock/stock_target_price/StockTargetPriceNotificationRestControllerDocsTest.java
- 종목 지정가 푸시 알림 비즈니스 로직을 비동기화로 변경
> [refactor] 종목 지정가 푸시 알림 리팩토링

- src/main/java/codesquad/fineants/spring/api/stock_target_price/response/TargetPriceNotificationSendItem.java
- src/main/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationService.java
- src/test/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationServiceTest.java
- src/test/java/codesquad/fineants/spring/docs/stock/stock_target_price/StockTargetPriceNotificationRestControllerDocsTest.java
- 종목 지정가 알림이 발송되었음에도 24시간 간격으로 무시하고 계속 발송되는 문제를 해결하였습니다.
> [fix] 종목 지정가 도달 알림 문제 해결

- src/main/java/codesquad/fineants/spring/config/WebConfig.java
- src/main/java/codesquad/fineants/spring/filter/CorsFilter.java
- cors 설정에서 오리진을 로컬 개발과 릴리즈 도메인으로 줄이기
> [feat] cors 설정

- src/main/java/codesquad/fineants/spring/api/notification/response/NotifyMessage.java
- Message 객체 생성시 Notification 객체를 넣지 않도록 변경
> [fix] 알림 전송 변경

- src/main/java/codesquad/fineants/spring/api/stock/service/StockService.java
- 종목 최신화 모듈 에러를 해결하였습니다.
- 원인 : 기존 stocks.tsv 파일을 이용한 종목 최신화 스케줄링 메서드가 작동하여 최신화된 데이터를 삭제한 것이 원인
> [fix] 종목 최신화 모듈 에러 해결

- src/main/java/codesquad/fineants/domain/common/count/valiator/CountNumber.java
- src/main/java/codesquad/fineants/domain/common/count/valiator/CountNumberValidator.java
- src/main/java/codesquad/fineants/domain/common/money/valiator/MoneyNumber.java
- src/main/java/codesquad/fineants/domain/common/money/valiator/MoneyValidator.java
- src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
- Money, Count 입력시 0값은 받지 않도록 변경
> [fix] 제약 조건 변경

- src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
- src/main/java/codesquad/fineants/domain/stock/Stock.java
- src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
- src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
- src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
- src/main/java/codesquad/fineants/spring/api/kis/manager/LastDayClosingPriceManager.java
- src/main/java/codesquad/fineants/spring/api/kis/service/KisService.java
- src/main/java/codesquad/fineants/spring/api/stock_target_price/response/TargetPriceNotificationSearchItem.java
- src/test/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspectTest.java
- src/test/java/codesquad/fineants/spring/api/kis/service/KisServiceTest.java
- src/test/java/codesquad/fineants/spring/api/stock/service/StockServiceTest.java
- src/test/java/codesquad/fineants/spring/api/stock_target_price/service/StockTargetPriceNotificationServiceTest.java
- src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
- src/test/java/codesquad/fineants/spring/docs/stock/StockRestControllerDocsTest.java
- 가격이 redis에 없는 경우 kis 서버에 질의하여 가져오도록 합니다.
> [feat] 종목의 현재가 및 종가 조회 메서드 수정

- src/main/java/codesquad/fineants/domain/fcm_token/FcmToken.java
- src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
- src/main/java/codesquad/fineants/spring/api/notification/event/PortfolioEventListener.java
- src/main/java/codesquad/fineants/spring/api/notification/service/NotificationService.java
- src/test/java/codesquad/fineants/spring/api/notification/service/NotificationServiceTest.java
- 목표수익률 비교시 기존 예산 + 총손익이 아닌 평가금액을 기준으로 비교하도록 설정
> [fix] 목표수익률 알림 버그 해결

- src/main/java/codesquad/fineants/spring/api/watch_list/response/ReadWatchListResponse.java
- dailyChangeRate 프로퍼티를 구현하여 null이 나오는 문제 해결
> [bug] Watchlist 조회 문제 해결

- src/main/java/codesquad/fineants/spring/api/member/response/OauthMemberResponse.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/test/java/codesquad/fineants/spring/docs/member/MemberRestControllerDocsTest.java
- 로그인(소셜 or 일반) 후 리스폰스에 notificationPreference, provider를 추가하여 응답하도록 구현
> [feat] 로그인시 provider 프로퍼티 추가

- src/main/java/codesquad/fineants/spring/api/member/response/LoginResponse.java
- src/main/java/codesquad/fineants/spring/api/member/response/OauthMemberLoginResponse.java
- src/main/java/codesquad/fineants/spring/api/member/response/ProfileResponse.java
- src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
- src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
- src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
- src/test/java/codesquad/fineants/spring/docs/member/MemberRestControllerDocsTest.java
- 로그인 리스폰스에서 user 프로퍼티 제거
- 프로필 조회 리스폰스에서 provider 프로퍼티 추가
> [fix] 로그인 및 프로필 조회 response 수정

- src/main/java/codesquad/fineants/domain/stock/Stock.java
- src/main/java/codesquad/fineants/domain/stock_dividend/StockDividend.java
- NullPointerException 문제를 해결하였습니다.
> [fix] Watchlist 조회 문제 해결

- src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
- src/test/java/codesquad/fineants/spring/api/portfolio/service/PortFolioServiceTest.java
- 포트폴리오 추가 및 수정시 검증 로직을 수정하였습니다.
> [fix] 포트폴리오 검증 로직 수정

- src/docs/asciidoc/api/exchange_rate.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/codesquad/fineants/domain/common/money/Percentage.java
- src/main/java/codesquad/fineants/domain/common/money/PercentageConverter.java
- src/main/java/codesquad/fineants/domain/exchange_rate/client/ExchangeRateWebClient.java
- src/main/java/codesquad/fineants/domain/exchange_rate/controller/ExchangeRateRestController.java
- src/main/java/codesquad/fineants/domain/exchange_rate/domain/dto/request/ExchangeRateCreateRequest.java
- src/main/java/codesquad/fineants/domain/exchange_rate/domain/dto/response/ExchangeRateDeleteRequest.java
- src/main/java/codesquad/fineants/domain/exchange_rate/domain/dto/response/ExchangeRateFetchResponse.java
- src/main/java/codesquad/fineants/domain/exchange_rate/domain/dto/response/ExchangeRateItem.java
- src/main/java/codesquad/fineants/domain/exchange_rate/domain/dto/response/ExchangeRateListResponse.java
- src/main/java/codesquad/fineants/domain/exchange_rate/domain/entity/ExchangeRate.java
- src/main/java/codesquad/fineants/domain/exchange_rate/repository/ExchangeRateRepository.java
- src/main/java/codesquad/fineants/domain/exchange_rate/service/ExchangeRateService.java
- src/main/java/codesquad/fineants/domain/member/service/MemberService.java
- src/main/java/codesquad/fineants/domain/member/service/WebClientWrapper.java
- src/main/java/codesquad/fineants/global/errors/errorcode/ExchangeRateErrorCode.java
- src/main/java/codesquad/fineants/global/success/ExchangeRateSuccessCode.java
- src/test/java/codesquad/fineants/docs/exchange_rate/ExchangeRateRestControllerDocsTest.java
- src/test/java/codesquad/fineants/domain/exchange_rate/domain/entity/ExchangeRateTest.java
- src/test/java/codesquad/fineants/domain/exchange_rate/service/ExchangeRateServiceTest.java
- src/test/java/codesquad/fineants/domain/member/service/MemberServiceTest.java
- src/test/java/codesquad/fineants/domain/notification/event/listener/PurchaseHistoryEventListenerTest.java
- 통화 환율에 대한 추가, 조회, 업데이트, 삭제, 기준통화 변경에 대한 API 및 서비스를 구현
> [feat] 환율 관리 기능 구현

- src/main/java/codesquad/fineants/domain/kis/client/KisAccessToken.java
- src/main/java/codesquad/fineants/domain/notification_preference/domain/entity/NotificationPreference.java
- src/main/resources/db/mysql/init-schema.sql
- src/test/java/codesquad/fineants/AbstractContainerBaseTest.java
- src/test/java/codesquad/fineants/domain/kis/aop/AccessTokenAspectTest.java
- src/test/java/codesquad/fineants/domain/kis/client/KisClientTest.java
- src/test/java/codesquad/fineants/domain/kis/service/KisAccessTokenRedisServiceTest.java
- src/test/java/codesquad/fineants/domain/kis/service/KisServiceTest.java
- src/test/java/codesquad/fineants/domain/notification/service/NotificationServiceTest.java
- src/test/java/codesquad/fineants/domain/portfolio/service/DashboardServiceTest.java
- src/test/java/codesquad/fineants/domain/portfolio/service/PortFolioServiceTest.java
- src/test/java/codesquad/fineants/domain/portfolio/service/PortfolioNotificationServiceTest.java
- src/test/java/codesquad/fineants/domain/portfolio_gain_history/service/PortfolioGainHistoryServiceTest.java
- src/test/java/codesquad/fineants/domain/portfolio_holding/controller/PortfolioHoldingRestControllerTest.java
- src/test/java/codesquad/fineants/domain/purchase_history/service/PurchaseHistoryServiceTest.java
- src/test/java/codesquad/fineants/domain/stock_dividend/service/StockDividendServiceTest.java
- src/test/java/codesquad/fineants/domain/stock_target_price/service/StockTargetPriceNotificationServiceTest.java
- src/test/java/codesquad/fineants/domain/watch_list/service/WatchListServiceTest.java
- Redis Test Container 추가로 인하여 Redis 모킹 코드를 제거
> [test] Redis 모킹 코드 제거

- src/docs/asciidoc/api/member_notification.adoc
- src/main/java/codesquad/fineants/domain/member/controller/MemberNotificationRestController.java
- src/main/java/codesquad/fineants/domain/portfolio_holding/domain/dto/response/PortfolioHoldingDetailItem.java
- src/main/java/codesquad/fineants/domain/portfolio_holding/domain/dto/response/PortfolioHoldingRealTimeItem.java
- src/test/java/codesquad/fineants/docs/RestDocsSupport.java
- src/test/java/codesquad/fineants/docs/member/MemberNotificationRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java
- src/test/java/codesquad/fineants/domain/member/controller/MemberNotificationRestControllerTest.java
- API 문서 수정
- 포트폴리오 조회시 각 종목에 대해서 dateAdded 프로퍼티 추가
- 불필요한 알림 읽음 API 제거
> #334 fix: API 수정

- src/test/java/codesquad/fineants/docs/member/MemberRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java
> [fix] 테스트 코드 오타 수정

- src/docs/asciidoc/api/exchange_rate.adoc
- src/main/java/codesquad/fineants/domain/portfolio_holding/domain/dto/response/PortfolioHoldingDetailItem.java
- src/main/java/codesquad/fineants/domain/portfolio_holding/domain/dto/response/PortfolioHoldingRealTimeItem.java
- src/test/java/codesquad/fineants/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java
> [feat] 포트폴리오 종목 조회 및 sse 응답의 프로퍼티 수정

- src/main/java/codesquad/fineants/domain/member/controller/OauthRestController.java
- src/main/java/codesquad/fineants/global/security/ajax/config/AjaxSecurityConfig.java
- src/main/java/codesquad/fineants/global/security/ajax/handler/AjaxAuthenticationSuccessHandler.java
- src/main/java/codesquad/fineants/global/security/factory/TokenFactory.java
- src/main/java/codesquad/fineants/global/security/oauth/dto/Token.java
- src/main/resources/application-release.yml
- src/test/java/codesquad/fineants/global/security/factory/TokenFactoryTest.java
- 쿠키 생성시 release 프로파일 한에서 secure 비활성화 설정
> [fix] 쿠키 설정 변경

- src/main/java/codesquad/fineants/global/security/oauth/config/OauthSecurityConfig.java
- src/main/java/codesquad/fineants/global/security/oauth/handler/OAuth2SuccessHandler.java
- 릴리즈 서버 한에서 쿠키의 secure=false로 설정
> #351 fix: oauth 로그인 쿠키 설정 변경

- src/main/java/codesquad/fineants/domain/member/controller/OauthRestController.java
- src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
> [fix] 테스트 비활성화 처리

- src/main/java/codesquad/fineants/domain/member/controller/OauthRestController.java
- src/main/java/codesquad/fineants/domain/notification/service/NotificationService.java
- src/main/java/codesquad/fineants/global/security/oauth/handler/OAuth2SuccessHandler.java
- src/main/java/codesquad/fineants/global/security/oauth/service/CustomOidcUserService.java
- src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
> [fix] oauth 로그인 설정 수정

- src/main/java/codesquad/fineants/domain/member/controller/OauthRestController.java
- src/main/java/codesquad/fineants/domain/notification/service/NotificationService.java
- src/main/java/codesquad/fineants/global/security/common/CommonSecurityConfig.java
- src/main/java/codesquad/fineants/global/security/oauth/handler/OAuth2SuccessHandler.java
- src/main/java/codesquad/fineants/global/security/oauth/service/CustomOidcUserService.java
- src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
> [fix] origin 추가

- src/main/java/codesquad/fineants/domain/member/controller/OauthRestController.java
- src/main/java/codesquad/fineants/domain/notification/service/NotificationService.java
- src/main/java/codesquad/fineants/global/security/common/CommonSecurityConfig.java
- src/main/java/codesquad/fineants/global/security/oauth/dto/OAuthAttribute.java
- src/main/java/codesquad/fineants/global/security/oauth/handler/OAuth2SuccessHandler.java
- src/main/java/codesquad/fineants/global/security/oauth/service/CustomOidcUserService.java
- src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
> [fix] 로깅 추가

- src/docs/asciidoc/api/authentication.adoc
- src/main/java/codesquad/fineants/global/security/oauth/dto/OAuthAttribute.java
- src/main/java/codesquad/fineants/global/util/CookieUtils.java
- src/test/java/codesquad/fineants/AbstractContainerBaseTest.java
- src/test/java/codesquad/fineants/docs/RestDocsSupport.java
- src/test/java/codesquad/fineants/docs/dividend/StockDividendRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/exchangerate/ExchangeRateRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/fcm/FcmRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/kis/KisRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/member/AuthenticationDocsTest.java
- src/test/java/codesquad/fineants/docs/member/MemberNotificationRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/member/MemberRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/notification/NotificationRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio/DashboardRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio/PortfolioNotificationRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio/PortfolioNotificationSettingRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio/PortfolioRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/portfolio_holding/PortfolioHoldingRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/purchase_history/PurchaseHistoryRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/stock/StockRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/stock/StockTargetPriceNotificationRestControllerDocsTest.java
- src/test/java/codesquad/fineants/docs/watch_list/WatchListRestControllerDocsTest.java
- src/test/resources/org/springframework/restdocs/templates/request-cookies.snippet
- Authorization 헤더 제거
- 회원 계정 삭제시 RequestBody 제거
- 인가가 필요한 API에 토큰 쿠키 추가
> [docs] Rest Docs 수정

- src/main/java/codesquad/fineants/global/security/oauth/filter/JwtAuthenticationFilter.java
- 액세스 및 리프레시 토큰 갱신하는 경우에만 리스폰스에 쿠키 설정하도록 변경
- 내용
> [fix] 액세스 토큰 갱신 수정

- src/main/java/codesquad/fineants/global/security/ajax/config/AjaxSecurityConfig.java
- src/main/java/codesquad/fineants/global/security/oauth/config/OauthSecurityConfig.java
- src/main/java/codesquad/fineants/global/security/oauth/filter/JwtAuthenticationFilter.java
- src/main/java/codesquad/fineants/global/util/CookieUtils.java
- src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
- 액세스 토큰 갱신시 중복된 Set-Cookie 헤더 생성하는 문제를 해결하였습니다.
> [fix] 중복 Set-Cookie 생성 문제 해결

- src/main/java/codesquad/fineants/global/security/common/CommonSecurityConfig.java
> [fix] cors 설정에서 오타 수정

- src/main/java/codesquad/fineants/global/security/common/CommonSecurityConfig.java
- src/test/java/codesquad/fineants/domain/member/controller/AuthenticationIntegrationTest.java
- 액세스 토큰 갱신 테스트에 문제가 있어서 임시 비활성화
> [test] 테스트 임시 비활성화 

- src/main/java/codesquad/fineants/domain/fcm/service/FcmService.java
- src/main/java/codesquad/fineants/domain/kis/service/KisService.java
- src/main/java/codesquad/fineants/domain/notification/domain/dto/response/NotifyMessage.java
- src/main/java/codesquad/fineants/domain/notification/domain/dto/response/PortfolioNotifyMessage.java
- src/main/java/codesquad/fineants/domain/notification/domain/dto/response/StockNotifyMessage.java
- src/main/java/codesquad/fineants/domain/notification/domain/dto/response/TargetPriceNotificationSaveResponse.java
- src/main/java/codesquad/fineants/domain/notification/domain/dto/response/save/NotificationSaveResponse.java
- src/main/java/codesquad/fineants/domain/notification/domain/dto/response/save/PortfolioNotificationSaveResponse.java
- src/main/java/codesquad/fineants/domain/notification/service/NotificationService.java
- src/test/java/codesquad/fineants/domain/notification/service/NotificationServiceTest.java
> [fix] 종목 지정가 알림 문제 해결

- .github/workflows/ci.cd.production.yml
- .github/workflows/ci.cd.release.yml
> [feat]action library version 수정

- src/main/java/codesquad/fineants/domain/stock/domain/entity/Stock.java
- src/main/java/codesquad/fineants/domain/stock/service/StockService.java
- src/main/java/codesquad/fineants/infra/s3/service/AmazonS3StockService.java
- src/test/java/codesquad/fineants/domain/stock/domain/entity/StockTest.java
- src/test/java/codesquad/fineants/infra/s3/service/AmazonS3StockServiceTest.java
- s3 stocks.csv 파일이 예상과 다르게 저장되는 문제를 해결하였습니다.
> [fix] s3 stocks.csv 버그 해결

- src/main/java/codesquad/fineants/global/common/authorized/AuthorizationAspect.java
- src/main/java/codesquad/fineants/global/common/resource/ResourceIdParser.java
- src/main/java/codesquad/fineants/global/security/ajax/entrypoint/CommonLoginAuthenticationEntryPoint.java
- 루트 경로 요청시 ResourceIdAspect에서 캐치되는 문제를 해결하였습니다.
> [fix] resourceId 문제 해결

- src/main/java/codesquad/fineants/domain/stock/service/StockService.java
- src/main/resources/application-local.yml
- src/main/resources/application-production.yml
- src/main/resources/application-release.yml
- 릴리즈 서버는 7시에 수행, 프로덕션은 8시에 스케줄링 수행
> feat: 종목 및 배당 일정 최신화 기능 cron 표현식 수정

- src/main/java/codesquad/fineants/domain/kis/aop/AccessTokenAspect.java
- src/main/java/codesquad/fineants/domain/kis/client/KisClient.java
- src/main/java/codesquad/fineants/domain/kis/repository/KisAccessTokenRepository.java
- src/main/java/codesquad/fineants/domain/kis/service/KisProductionScheduledService.java
- src/main/java/codesquad/fineants/domain/kis/service/KisService.java
- src/main/java/codesquad/fineants/global/init/SetupDataLoader.java
- src/test/java/codesquad/fineants/domain/kis/service/KisServiceTest.java
- src/test/java/codesquad/fineants/global/init/SetupDataLoaderTest.java
- 한국투자증권 액세스 토큰 만료 1시간전에 재발급하도록 설정
- 프로덕션 서버에서만 현재가 스케줄링 메서드를 실행하도록 버그 수정
> [fix] 액세스 토큰 Aspect 수정

- src/main/java/codesquad/fineants/domain/dividend/domain/entity/StockDividend.java
- src/main/java/codesquad/fineants/domain/dividend/repository/StockDividendRepository.java
- src/main/java/codesquad/fineants/domain/portfolio/domain/entity/Portfolio.java
- src/main/java/codesquad/fineants/domain/stock/repository/StockRepository.java
- src/main/java/codesquad/fineants/domain/stock/service/StockAndDividendManager.java
- src/test/java/codesquad/fineants/AbstractContainerBaseTest.java
- src/test/java/codesquad/fineants/domain/holding/service/PortfolioHoldingServiceTest.java
- 포트폴리오 엔티티 클래스에 LocalDateTimeService 필드 추가
- 추가 이유는 모킹하기 위해서, 기본적으로 DefaultLocalDateTimeService를 초기화하여 사용함
- 배당금 엔티티 필드에 isDeleted 추가
> [feat] 배당금 엔티티에 필드 추가 및 포트폴리오 필드 추가

- src/main/java/codesquad/fineants/domain/kis/scheduler/KisClosingPriceScheduler.java
- src/main/resources/application-production.yml
> fix: 갱신 주기 오타 수정

- src/main/java/co/fineants/api/domain/portfolio/reactive/PortfolioObserver.java
- 실시간 포트폴리오 정보 조회시 500 에러가 발생하는 것을 해결하였습니다. 
- #459
> [fix] sse 버그 해결

- src/main/java/co/fineants/api/global/security/common/config/CommonSecurityProductionConfig.java
- src/main/java/co/fineants/api/global/security/common/config/CommonSecurityReleaseConfig.java
- 프로덕션 서버 대상으로는 localhost 에서 접근하지 못하도록 수정
- 릴리즈 서버 대상으로는 localhost:3000 오리진에서 접근할 수 있도록 추가
> [feat] cors 설정 수정

- src/main/java/co/fineants/price/domain/stockprice/client/StockPriceWebSocketHandler.java
- 메시지 수신시 페이로드 내용을 출력할 수 있도록 로깅 추가
> [feat] 로깅 추가

- src/main/java/co/fineants/price/domain/stockprice/client/StockPriceWebSocketClient.java
- src/main/java/co/fineants/price/domain/stockprice/client/StockPriceWebSocketHandler.java
- src/main/java/co/fineants/price/domain/stockprice/scheduler/StockPriceWebSocketScheduler.java
- 한국투자증권 서버로부터 핑퐁 데이터 수신시 웹소켓 연결 유지를 위한 퐁 데이터 송신 기능 구현
- 웹소켓의 세션이 예상치 못하게 끊기는 경우 재연결하는 기능 구현
> [feat] 퐁 데이터 송신 구현

- src/main/java/co/fineants/api/domain/holding/service/PortfolioObservableService.java
- src/main/java/co/fineants/api/domain/kis/scheduler/KisAccessTokenScheduler.java
- src/main/java/co/fineants/api/domain/kis/scheduler/KisProductionScheduler.java
- src/main/java/co/fineants/price/domain/stockprice/client/StockPriceEventListener.java
- src/main/java/co/fineants/price/domain/stockprice/client/StockPriceWebSocketClient.java
- src/main/java/co/fineants/price/domain/stockprice/client/StockPriceWebSocketHandler.java
- src/main/java/co/fineants/price/domain/stockprice/client/WebSocketApprovalKeyReissueEvent.java
- src/main/java/co/fineants/price/domain/stockprice/config/StockPriceConfig.java
- src/main/java/co/fineants/price/domain/stockprice/domain/StockPrice.java
- src/main/java/co/fineants/price/domain/stockprice/factory/StockPriceWebSocketMessageFactory.java
- src/main/java/co/fineants/price/domain/stockprice/repository/StockPriceRepository.java
- src/main/java/co/fineants/price/domain/stockprice/scheduler/StockPriceScheduler.java
- src/main/java/co/fineants/price/domain/stockprice/service/StockPriceService.java
- src/test/java/co/fineants/api/domain/holding/controller/PortfolioHoldingRestControllerIntegrationTest.java
- src/test/java/co/fineants/price/domain/stockprice/repository/StockPriceRepositoryTest.java
- 만료된 종목에 대하여 구독을 해제하는 기능 구현
- 웹소켓 승인키 에러 메시지에 대한 재발급 이벤트 추가
> [feat] 종목 실시간 체결가 해제 기능 구현

- src/main/java/co/fineants/api/global/security/factory/CookieDomainProvider.java
- src/main/java/co/fineants/api/global/security/factory/DeployCookieDomainProvider.java
- src/main/java/co/fineants/api/global/security/factory/LocalCookieDomainProvider.java
- src/main/java/co/fineants/api/global/security/factory/TokenFactory.java
- src/test/java/co/fineants/AbstractContainerBaseTest.java
- src/test/java/co/fineants/api/docs/RestDocsSupport.java
- CookieDomainProvider 인터페이스 추가에 따른 테스트 코드들의 컴파일 에러 해결
> [fix] 테스트 컴파일 에러 해결

- src/main/java/co/fineants/api/domain/dividend/domain/entity/DividendDates.java
- src/main/java/co/fineants/api/domain/dividend/domain/entity/StockDividend.java
- src/main/java/co/fineants/api/domain/holding/domain/chart/DividendChart.java
- src/main/java/co/fineants/api/domain/holding/domain/chart/PieChart.java
- src/main/java/co/fineants/api/domain/holding/domain/chart/SectorChart.java
- src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioDividendChartItem.java
- src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioHoldingDetailItem.java
- src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioHoldingItem.java
- src/main/java/co/fineants/api/domain/holding/domain/dto/response/PortfolioHoldingRealTimeItem.java
- src/main/java/co/fineants/api/domain/holding/domain/entity/PortfolioHolding.java
- src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioHoldingDetailFactory.java
- src/main/java/co/fineants/api/domain/holding/repository/PortfolioHoldingRepository.java
- src/main/java/co/fineants/api/domain/holding/service/PortfolioHoldingService.java
- src/main/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculator.java
- src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java
- src/main/java/co/fineants/api/domain/purchasehistory/domain/entity/PurchaseHistory.java
- src/main/java/co/fineants/api/domain/purchasehistory/service/PurchaseHistoryService.java
- src/main/java/co/fineants/api/domain/stock/domain/dto/response/StockResponse.java
- src/main/java/co/fineants/api/domain/stock/domain/entity/Stock.java
- src/test/java/co/fineants/api/domain/holding/controller/PortfolioHoldingRestControllerTest.java
- src/test/java/co/fineants/api/domain/holding/domain/entity/PortfolioHoldingTest.java
- src/test/java/co/fineants/api/domain/holding/service/PortfolioHoldingServiceTest.java
- src/test/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculatorTest.java
- src/test/java/co/fineants/api/domain/portfolio/service/DashboardServiceTest.java
- src/test/java/co/fineants/api/domain/portfolio/service/PortFolioServiceTest.java
- src/test/java/co/fineants/api/domain/purchasehistory/domain/entity/PurchaseHistoryTest.java
- src/test/java/co/fineants/api/domain/purchasehistory/service/PurchaseHistoryServiceTest.java
- 테스트의 객체 생성시 의존관계 문제 해결하여 테스트 실패 해결
> [fix] 테스트 실패 해결

- src/main/java/co/fineants/api/domain/common/count/Count.java
- src/main/java/co/fineants/api/domain/common/money/Money.java
- src/main/java/co/fineants/api/domain/holding/domain/chart/SectorChart.java
- src/main/java/co/fineants/api/domain/holding/domain/entity/PortfolioHolding.java
- src/main/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculator.java
- src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java
- src/main/java/co/fineants/api/domain/portfolio/service/DashboardService.java
- src/test/java/co/fineants/api/domain/common/money/MoneyTest.java
- src/test/java/co/fineants/api/domain/holding/domain/entity/PortfolioHoldingTest.java
- src/test/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculatorTest.java
- 포트폴리오 종목에 있는 계산 메서드들을 Calculator 클래스로 이동
- Calculator 클래스 메서드에 javadoc 추가
- Calculator 클래스 메서드의 테스트 코드 추가
- Portfolio 클래스의 계산 메서들을 Calculator로 이동
> [refactor] 포트폴리오 종목 및 계산기 개선

- src/main/java/co/fineants/api/domain/member/service/MemberService.java
- src/main/java/co/fineants/api/global/security/factory/TokenFactory.java
- src/main/java/co/fineants/api/global/security/oauth/dto/Token.java
- 로그아웃 서비스에 액세스토큰, 리프레시 토큰 쿠키의 만료하는 기능 추가
> [feat] 로그아웃 서비스 수정

- src/main/java/co/fineants/api/domain/holding/domain/chart/PieChart.java
- src/main/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculator.java
- src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java
- src/main/java/co/fineants/api/domain/portfolio/domain/entity/PortfolioFinancial.java
- src/test/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculatorTest.java
- PortfolioCalculator 클래스의 계산 메서드에 대한 테스트 추가
- 남은 계산 메서드에 대해서도 테스트 코드 추가
> [test] Calculator 클래스에 테스트 추가

- src/test/java/co/fineants/api/domain/portfolio/domain/calculator/PortfolioCalculatorTest.java
- PortfolioCalculator의 테스트 코드 추가
> [test] Calualtor 테스트 코드 추가

- src/docs/asciidoc/api/portfolio.adoc
- src/main/java/co/fineants/api/domain/BaseEntity.java
- src/main/java/co/fineants/api/domain/portfolio/controller/PortFolioRestController.java
- src/main/java/co/fineants/api/domain/portfolio/domain/dto/response/PortfolioNameItem.java
- src/main/java/co/fineants/api/domain/portfolio/domain/dto/response/PortfolioNameResponse.java
- src/main/java/co/fineants/api/domain/portfolio/domain/entity/Portfolio.java
- src/main/java/co/fineants/api/domain/portfolio/service/PortFolioService.java
- src/main/java/co/fineants/api/global/success/PortfolioSuccessCode.java
- src/test/java/co/fineants/api/docs/portfolio/PortfolioRestControllerDocsTest.java
- src/test/java/co/fineants/api/domain/portfolio/service/PortFolioServiceTest.java
- 포트폴리오 이름 목록 API(GET /api/portfolios/names) 구현
- 테스트 코드 추가
> [feat] 포트폴리오 이름 목록 API 구현

- src/main/java/co/fineants/api/global/filter/SignupLoggingFilter.java
- src/main/java/co/fineants/api/infra/s3/service/AmazonS3DividendService.java
- src/main/java/co/fineants/api/infra/s3/service/AmazonS3Service.java
- src/main/java/co/fineants/api/infra/s3/service/AmazonS3StockService.java
- BufferedReader와 같은 입출력 리소스 사용시 try-with-resources 방식으로 개선
> [refactor] 입출력 리소스 개선

- src/main/java/co/fineants/api/domain/common/money/Money.java
- src/main/java/co/fineants/api/domain/common/money/RateDivision.java
- src/test/java/co/fineants/api/domain/common/money/MoneyTest.java
- src/test/java/co/fineants/api/domain/common/money/RateDivisionTest.java
- 0 나누기 예외 처리 추가
- 0 나누기에 대한 테스트 코드 추가
> [feat] Money 연산간의 예외 처리

- README.md
> [docs] README 수정

- src/main/java/co/fineants/api/domain/holding/repository/PortfolioHoldingRepository.java
- src/main/java/co/fineants/api/domain/kis/client/KisClient.java
- src/main/java/co/fineants/api/domain/kis/domain/dto/response/KisErrorResponse.java
- src/main/java/co/fineants/api/domain/kis/scheduler/KisProductionScheduler.java
- src/main/java/co/fineants/api/domain/kis/service/KisService.java
- src/main/java/co/fineants/api/domain/stock_target_price/event/publisher/StockTargetPricePublisher.java
- src/main/java/co/fineants/api/domain/stock_target_price/repository/StockTargetPriceRepository.java
- src/test/java/co/fineants/api/domain/holding/repository/PortfolioHoldingRepositoryTest.java
- src/test/java/co/fineants/api/domain/stock_target_price/repository/StockTargetPriceRepositoryTest.java
- 쿼리 수정
- 요청 횟수 초과시 로깅하지 않도록 변경
> [feat] 쿼리 수정

- src/main/java/co/fineants/api/domain/helath/HealthCheckRestController.java
- src/main/java/co/fineants/api/global/security/oauth/config/OauthSecurityConfig.java
> Release 0.0.13

- src/main/resources/application-production.yml
- src/main/resources/application-release.yml
- production : 443 -> 8080
- release : 444 -> 9000
> fix: 포트 수정

- src/main/java/co/fineants/api/domain/holiday/controller/HolidayRestController.java
> [fix] 국내 휴장 일정 업데이트 API 매개변수 변환 문제 해결

- src/main/java/co/fineants/api/global/aspect/HttpLoggingAspect.java
- src/main/java/co/fineants/api/global/aspect/ServiceLogAspect.java
- src/main/resources/logback-spring.xml
- test 프로파일에서는 로깅 제외하도록 설정
- test 수행중에는 파일 로깅하지 않도록 설정
> [fix] AOP 설정 변경

- .github/workflows/ci.cd.release.yml
> [fix] aws deploy 명령어 오타 수정

- scripts/deploy/after-install.sh
- scripts/deploy/start.sh
- scripts/setup_cron.sh
- setup_cron.sh 스크립트 관련 경로 오타 수정
- after-install.sh 스크립트 실행중 환경별 디렉토리(release, production)가 존재하지 않으면 디렉토리 생성하는 코드 추가
> [fix] 배포 스크립트 오타 수정

- Dockerfile
> fix: Dockerfile 오타 수정

- Dockerfile
- scripts/deploy/stop.sh
- ENTRYPOINT 명령문에서 ARG 변수를 해석하지 못하여 문자열로 수정함
> [fix] Dockerfile 수정

- .github/workflows/ci.cd.production.yml
- .github/workflows/ci.cd.release.yml
- Dockerfile
- docker-compose.production.yml
- docker-compose.release.yml
- scripts/deploy/after-install.sh
- scripts/deploy/start.sh
- scripts/deploy/stop.sh
- 배포 스크립트의 경로를 변수로 설정하여 개선
- Dockerfile에 메타 데이터 추가
> [infra] 배포 스크립트 수정

- src/test/java/co/fineants/api/global/init/SetupDataLoaderTest.java
- setupDataLoader 테스트 코드에서 csv 파일을 롤백하는 코드 추가
- 코드 추가 이유는 순서에 따라서 다른 테스트에 영향을 미치기 때문
> [test] rollback 코드 추가

- .github/workflows/ci.cd.production.yml
- .gitignore
- build.gradle
- docker-compose.local.yml
- docker-compose.production.yml
- prometheus/config/local/prometheus.yml
- prometheus/config/local/rule.yml
- prometheus/config/prod/prometheus.yml
- prometheus/config/prod/rule.yml
- src/main/java/co/fineants/api/global/security/oauth/config/OauthSecurityConfig.java
- src/main/resources/application.yml
- Spring Boot의 CPU, 메모리와 같은 리소스 사용량을 모니터링하기 위해서 프로메테우스를 추가하였습니다.
> [Infra] prometheus 추가

- prometheus/config/prod/prometheus.yml
- scripts/deploy/start.sh
- spring boot 앱의 호스트 주소 변경
- prometheus 디렉토리 실행 권한을 설정하는 쉘 스크립트 추가
> [fix] 프로메테우스 설정 오타 수정

- .github/workflows/ci.cd.production.yml
- .github/workflows/ci.cd.release.yml
> [fix] 캐시 버전 수정

- src/main/java/co/fineants/api/infra/mail/config/EmailSenderConfig.java
- src/main/resources/application.yml
> fix: 이메일 설정

- docker-compose.local.yml
- docker-compose.production.yml
- 프로메테우스 알림에 JVM 사용량 알림 설정 추가
- alertmanager 컨테이너 추가하고 프로메테우스가 alertmanager를 통해서 알림을 보내도록 설정하였습니다.
- 해당 알림은 프로덕션 서버만 해당됩니다.
> [feat] 프로메테우스 및 alertmanager 설정 추가

- .gitignore
- build.gradle
- src/main/resources/application-local.yml
- src/main/resources/application-production.yml
- src/main/resources/application-release.yml
- src/main/resources/application.yml
- src/main/resources/db/mysql/migration/V1__init.sql
- src/main/resources/db/mysql/migration/V2__add_index.sql
- flyway 의존성 라이브러리 추가
- 데이터베이스 테이블 초기화 및 복합 인덱스 추가하는 스크립트 추가
- release, proudction 환경 대상으로 ddl-auto=validate로 변경
> [refactor] flyway 라이브러리 추가

- .gitignore
- src/main/java/co/fineants/api/domain/gainhistory/repository/PortfolioGainHistoryRepository.java
- src/main/resources/db/mysql/migration/V1__init.sql
- src/main/resources/db/mysql/migration/V2__add_index.sql
- src/main/resources/db/mysql/migration/V3__add_index_email_provider.sql
- MemberRepository의 쿼리 메서드를 대상으로 복합 인덱스를 생성하여 성능 개선
- 300만건의 회원 데이터가 있는 상태에서 쿼리 실행시 기존 **1252ms에서 33ms로 37.9배 개선**되었습니다.
- 회원가입 API를 대상으로 성능 측정시 기존 **1720ms -> 561ms로 3.06배 개선**된 것을 볼수 있습니다.
> [feat] 회원 쿼리 성능 개선

- src/main/java/co/fineants/api/domain/member/controller/SignUpRestController.java
- src/main/java/co/fineants/api/domain/member/service/MemberService.java
- src/main/java/co/fineants/api/domain/member/service/SignupVerificationService.java
- src/test/java/co/fineants/api/docs/member/SignUpRestControllerDocsTest.java
- src/test/java/co/fineants/api/domain/member/controller/SignUpRestControllerTest.java
- src/test/java/co/fineants/api/domain/member/service/MemberServiceTest.java
- src/test/java/co/fineants/api/domain/member/service/SignupVerificationServiceTest.java
- src/test/java/co/fineants/config/TestConfig.java
- SignupRestController에서 더이상 MemberService를 의존하지 않도록 개선, 대신에 SignupVerificationService로 기존 메서드를 이전
> [refactor] MemberService 개선

- src/main/java/co/fineants/api/domain/holding/service/PortfolioObservableService.java
- src/main/java/co/fineants/api/domain/portfolio/config/ObserverFactoryConfig.java
- src/main/java/co/fineants/api/domain/portfolio/domain/factory/ObserverFactory.java
- src/main/java/co/fineants/api/domain/portfolio/domain/factory/PortfolioObserverFactory.java
- src/main/java/co/fineants/api/domain/portfolio/domain/factory/StockMarketObserverFactory.java
- src/main/java/co/fineants/api/domain/portfolio/reactive/PortfolioObserver.java
- src/main/java/co/fineants/api/domain/portfolio/reactive/StockMarketObserver.java
- src/main/resources/application.yml
- src/main/resources/portfolio.yml
- src/main/resources/sse.yml
- src/test/java/co/fineants/api/domain/portfolio/domain/factory/PortfolioObserverFactoryTest.java
- src/test/java/co/fineants/api/domain/portfolio/domain/factory/StockMarketObserverFactoryTest.java
- SSE 이벤트에 id, reconnectTime 추가
- OberserFactory 인터페이스 및 구현체 추가
> [feat] SSE 이벤트에 id, reconnectTime 추가

- src/main/java/co/fineants/api/domain/holding/config/PortfolioStreamerFactoryConfig.java
- src/main/java/co/fineants/api/domain/holding/domain/factory/PortfolioStreamMessageConsumerFactory.java
- src/main/java/co/fineants/api/domain/holding/service/sender/StreamContinuesMessageSender.java
- src/test/java/co/fineants/api/domain/holding/service/sender/StreamContinuesMessageSenderTest.java
> [fix] 필드 멤버 제거

- src/main/java/co/fineants/api/domain/stock/domain/dto/request/StockSearchRequest.java
- src/main/java/co/fineants/api/domain/stock/repository/StockQueryRepository.java
- src/main/java/co/fineants/api/domain/stock/repository/StockRepository.java
- src/main/java/co/fineants/api/domain/stock/service/StockService.java
- src/test/java/co/fineants/api/domain/stock/service/StockServiceTest.java
> [refactor] 종목 검색 개선

- .github/workflows/ci.cd.release.yml
- Github Action Runner 버전 변경
- ubuntu-20.04 -> ubuntu-22.04
> [fix] Github Action 문제 해결

- src/main/resources/logback-spring.xml
- 릴리즈 서버 실행 에러를 파악하기 위해서 로깅 레벨을 DEBUG로 변경
- 에러 해결 후 추후 INFO로 변경할 예정
> [fix] 로깅 레벨 변경

- build.gradle
- docker-compose.local.yml
- src/main/resources/application-release.yml
- src/main/resources/logback-spring.xml
> [fix] flyway 디버깅 레벨 추가

- Dockerfile
- Dockerfile.production
- deploy/gcp/Dockerfile
- deploy/gcp/docker-compose.production.yml
- src/main/resources/application.yml
- src/test/java/co/fineants/api/infra/s3/service/imple/GoogleCloudStorageWriteProfileImageFileServiceTest.java
- src/test/java/co/fineants/config/GoogleCloudStorageTestConfig.java
- GCP Compute Engine에서 실행할 프로덕션용 docker-compose 파일 추가
> [infra] docker-compose 파일 추가

- scripts/backup_mysql_data.sh
- 하루에 한번 GCS Bucket에 백업하는 MySQL 데이터 백업 스크립트 구현
> [infra] MySQL 데이터 백업 스크립트 작성

- src/test/java/co/fineants/TestDataFactory.java
- src/test/java/co/fineants/api/domain/member/service/MemberServiceTest.java
- src/test/java/co/fineants/api/domain/member/service/SignupServiceTest.java
- src/test/java/co/fineants/api/domain/member/service/SignupValidatorServiceTest.java
- MemberService 클래스의 signup 메서드 제거
- SignupService 클래스의 signup 메서드 테스트 코드 추가
> [test] SignupService 테스트 추가

- src/main/java/co/fineants/api/domain/member/service/MemberService.java
- src/test/java/co/fineants/TestDataFactory.java
- src/test/java/co/fineants/api/domain/member/service/MemberServiceTest.java
- src/test/java/co/fineants/api/domain/member/service/SignupServiceTest.java
- src/test/java/co/fineants/api/domain/member/service/SignupValidatorServiceTest.java
> [test] 회원가입 서비스 테스트 추가
